### ISSUE TITLE
Chore: fix updating of document content when document is deleted

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#1009]
Otherwise we can't delete documents from the admin area

**Comment by actlikewill** [comment]
@longhotsummer I cant seem to be able to reproduce this. When I delete locally, everything is working fine and cascading as it should. It then re-extracts citations for the work which I don't think affects the document content.

**Comment by longhotsummer** [comment]
Doesn't seem to be any issue any more.
