### ISSUE TITLE
Add a menu item for Speeches & Law Reform Reports on ZambiaLII

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#1025]
To display the Speech nature of generic documents
https://new.zambialii.org/admin/peachjam/genericdocument/

![image](https://user-images.githubusercontent.com/46931873/225558123-1fe58b9d-b151-4f34-9988-99cff528a7ee.png)

**Comment by longhotsummer** [comment]
@nickmwangemi this should be two separate menu items:

1. one for "Speeches" - /doc/speech (documents exist)
2. one for "Law Reform Reports" - /doc/law-reform-report (document's don't seem to exist yet)

The document natures are here: https://new.zambialii.org/admin/peachjam/documentnature/
