### ISSUE TITLE
Increase the file size upload limit to 30MB starting with ZambiaLII

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#1026]
I have a law reform report that is 25MB and cannot be reduced further. We will have documents such as this one and we need to accommodate them under the LIIs.

**Comment by longhotsummer** [comment]
Please update the deployment docs at the same time: https://github.com/laws-africa/peachjam/blob/main/DEPLOYMENT.md#set-nginx-proxy-read-timeout

The mechanism for doing this is to copy a file into the dokku app's `nginx.conf.d` directory:

ubuntu@liiweb2:/home/dokku/lawlibrary-peachjam$ cat nginx.conf.d/agp.conf
client_max_body_size 500M;

I suggest we store that file in this repo, and then put it in place manually (there's no automatic way to get it from the repo into the right place).
