### ISSUE TITLE
Correctly use configured label for "author" field in search and listing views

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#1034]
In the filtered search results authors are displayed as Regional body. On peachjam, authors can be authors of generic documents, manuals, etc. and would not always be official organs of some sort. 
https://www.lawlibrary.org.za/search/?q=murder
![image](https://user-images.githubusercontent.com/46931873/226087654-304cb01e-9f50-4968-b803-77a246b416a8.png)

**Comment by longhotsummer** [comment]
Currently `Regional body` is the label applied to the facet on the `author` field, which is used by GenericDocument and LegialInstrument.

For AfricanLII, we're effectively using the `author` attribute as a way of linking to the regional body, hence the label. 

While the label is configurable, we're not using the configured setting in all places:

1. peachjam_search.views.SearchView
2. peachjam/js/components/ListFacets.vue

I had originally thought we'd mixed the `actor` part of the FRBR URI with author, but they are totally separate.

**Comment by longhotsummer** [comment]
When injecting this into the page to be used by javascript, we're going to be used the translated value (because the label is declared as `label = _("Author")` for example). So the javascript should not try to re-translate that value.
