### ISSUE TITLE
Accommodate briefing papers better

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#1035]
Briefing papers are currently filed under Generic Document on the agp website. This presents some limitations:
- it forces the selection of a jurisdiction, which is not always relevant
- it does not allow for the association of more than one author
- it might end up being listed under the jurisdiction and locality selected at upload

We should either allow that there is more than one author for a generic document, or we modify the article content type to accept PDF uploads and have nature associated with it. 

Example:
https://agp.africanlii.org/akn/aa-au/doc/briefing-paper/2021-08-30/data-for-governance-alliance-policy-submission-no1-submission-to-the-african-unions-african-commission-on-human-and-peoples-rights-achpr-on-the-thematic-report-on-declarations-of-state-of-emergency-and-state-of-disaster-laws-and-practices-in-africa/eng@2021-08-30

**Comment by NotoriousMBB** [comment]
It has also added the authors to the list of regional bodies on the front page
![image](https://user-images.githubusercontent.com/46931873/226533106-313eddfd-4918-4878-9d00-409e4f435ad0.png)

**Comment by NotoriousMBB** [comment]
Pleased to see citation extraction worked though

![image](https://user-images.githubusercontent.com/46931873/226533266-e478a220-503e-4ac7-9bd9-85896dff41f2.png)

**Comment by longhotsummer** [comment]
The inclusion of incorrect regional bodies on the homepage will be fixed by #902. The way we do it right now is a hack vulnerable to exactly the issue we're seeing here.

**Comment by longhotsummer** [comment]
This is now done.
