### ISSUE TITLE
Capitalize LII in uLII search box. All LIIs should be presented as Uppercase.

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1099]
![Image](https://user-images.githubusercontent.com/57619722/231699784-dd993e6b-9007-458f-bdad-59980cb32497.png)

![Image](https://user-images.githubusercontent.com/57619722/231700298-a98d9cc7-5e93-4aee-81d7-cd1b3339118b.png)

**Comment by longhotsummer** [comment]
This is derived from the `APP_NAME` environment variable and needs to be configured via dokku.

**Comment by longhotsummer** [comment]
Done for ULII.
