### ISSUE TITLE
New menu item on lawlibrary: South African Law Reform Commission

### ISSUE THREAD

**Issue by IngeNuWitty** [laws-africa/peachjam#1102]
We need a new menu item "South African Law Reform Commission" alongside Gazettes, etc. at the top of the home page, which leads to a landing page with a collection of Law Reform Commission documents. These documents should be generic documents with the following types:
Issue paper
Discussion paper
Law Reform Report
Media statement
All of these documents are related to a particular Project, so it would be ideal to have a new metadata field "Project" for all SALRC documents so that the user could filter by Project to see all papers associated with a project.

**Comment by longhotsummer** [comment]
Closing for now. Can be re-opened if/when necessary.
