### ISSUE TITLE
Logos on the home page appear too small, the home page needs a redesign to display them more prominently

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1116]
The ULII Logo that's more transparent and high resolution is to be added to the ULII homepage as the first logo before the AfricanLII logo and Laws.Africa logo.

![Image](https://user-images.githubusercontent.com/57619722/237051449-d076009a-81bb-406e-ba6c-fcb09d7d15ee.png)

**Comment by longhotsummer** [comment]
# Proposal

Issues that this tries to resolve:

* logos to small
* colour logos and coloured links on coloured/image background are difficult to read
* “advanced search” not obvious enough on some backgrounds

So:

1. move logos and search box below image banner
2. center search box (ala https://gazettes.africa/)
3. center logos, make bigger

![Image](https://github.com/laws-africa/peachjam/assets/4178542/68d5f305-b0ae-4d3d-a1b2-5af9f027836e)
