### ISSUE TITLE
Changes to the TCILII footer information.

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1121]
The list of liis is not required for this particular lii. Let's remove that.
What's required:

- About TCILII
- Flag
- Useful links(Refer to old site)
- World Law Resources (Also refer to the old site)

**Comment by NotoriousMBB** [comment]
Remove this block
![image](https://user-images.githubusercontent.com/46931873/234007392-35505a6b-e89b-44b7-96b2-5538bbdb6b46.png)
and replace with 
![image](https://user-images.githubusercontent.com/46931873/234007506-c2601737-0433-450c-9ec2-b241732837c0.png)

**Comment by NotoriousMBB** [comment]
This must go below **Our partners**
![image](https://user-images.githubusercontent.com/46931873/234007604-3bf71c74-5e14-4c8d-b08e-51e312d9152e.png)
