### ISSUE TITLE
As an admin I want the system to re-extract citations when new documents are uploaded.

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#1156]
* it's expensive, so if I upload 3 documents over the course of an hour (say), it should only do it after they're all uploaded
* do it intelligently: if I upload a document at date D, then only documents newer than D could have cited D, so only re-check those.

Without this, citation extraction is not happening correctly and users are missing out, in particular when old judgments are uploaded for the first time, or when alternative citations are added to existing judgments.

**Comment by longhotsummer** [comment]
Rough idea:

* create a new database model to track the state required (more below)
* when a document with date D is added to the site, we need to store in the db that all documents created at D or later must be re-indexed for search
* if the database already has a value (eg. B), then we only care if D < B.
* setup a background task (with `remove_existing=True`) to re-extract citations from documents, with a start delay of (say) 1 hour
* that task only re-extracts citations from documents with dates >= the value stored in the db.

**Comment by longhotsummer** [comment]
@actlikewill pls do a more in-depth proposal for this, I've provided a rough outline above.

**Comment by actlikewill** [comment]
### CitationProcessing Model

- We add a model called __CitationProcessing__ and give it following fields:
  - __processing_date__ - DateTimeField
  - __is_completed__ - BooleanField
- Add a method called extract_citations that will filter for documents with date ***on or after*** the processing_date
- For each document call the extract_citations method on it, (call model_save to reindex?, or bulk reindex the same queryset)

### Signal
- New instances of the model are created on the post save signal after a document has been created.
- We create and new instance and set the date of the created document as the processing_date. If an new document is created, we update the instance if the date of the new document is earlier than the processing date.

### Background Task
- We kick of the background task in the same signal above. It accepts the id of the CitationProcessing model and calls the extract citations method and marks it as completed.

**Comment by longhotsummer** [comment]
Looks good! This is ready to be scheduled re-prioritised for implementation.
