### ISSUE TITLE
Chore: ensure google understand the language of the site it is indexing

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#1159]
Google gets the language version of the site that is the site's default. That is English in most cases, except for ZanzibarLII and TanzLII. Ensure that we're telling Google:

1. that a language variants exist
2. what language it is getting
3. [x] the language of the document content if/when it differs from the site language

See:

* https://developers.google.com/search/docs/specialty/international/localized-versions
* https://developers.google.com/search/docs/specialty/international/managing-multi-regional-sites

**Comment by longhotsummer** [comment]
* Google ignores attributes like `lang` and determines the language on the page itself
* Google doesn't use cookies so it will get the default language version of a site
* Google recommends different URLs for different languages. Unfortunately we don't do this currently.

So at this point we can't make substantive changes *in general*.

Later, we may want to change our site URLs to be language based, so that we can tell google to index them separately (although the actual content wouldn't change).

We can, however, indicate alternate languages for document pages since we have language codes in the URL, eg:

* https://lawlibrary.org.za/akn/za/act/1996/constitution/eng@2013-08-23
* https://lawlibrary.org.za/akn/za/act/1996/constitution/xho@2013-08-23
* https://lawlibrary.org.za/akn/za/act/1996/constitution/zul@2013-08-23

We definitely want to help google crawl those and realise that they're the same document in different languages. This is particularly NB for AGP content.

**Comment by actlikewill** [comment]
@longhotsummer if we were to configure different urls for different languages would that mean a new app per language or is there a work around django can provide?

**Comment by longhotsummer** [comment]
Django supports this natively.Greg--(iPhone)On 17 May 2023, at 8:22 PM, actlikewill ***@***.***> wrote:﻿
@longhotsummer if we were to configure different urls for different languages would that mean a new app per language or is there a work around django can provide?
