### ISSUE TITLE
Add Training Video to the AGP site

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1162]
Add the video on how to use the platform to the agp website.
`https://www.youtube.com/watch?v=m54qqXDkCfk&t=186s&ab_channel=AfricanLII`

**Comment by longhotsummer** [comment]
I've added it to https://laws-africa.gitbook.io/africanlii/

**Comment by longhotsummer** [comment]
The idea is to implement this:


![Image](https://github.com/laws-africa/peachjam/assets/4178542/0d363d85-7a02-45bc-9070-df40b37e568b)



<iframe width="100%" height="100%" src="https://www.youtube.com/embed/m54qqXDkCfk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
