### ISSUE TITLE
Add menu Items To SeyLII Homepage.

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1170]
Add the following as menu items:

1. Finding Aids
2. Academic Papers- This will contain articles and books
3. Speeches and Presentations.

Update the blurb to include "SeyLII is a non-profit organisation and publishes the law of the Seychelles for free online access."

**Comment by nickmwangemi** [comment]
@longhotsummer Are these menu items document natures or taxonomies?
