### ISSUE TITLE
As a user, I want to be able to remove an uploaded file when editing Judgments.

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1196]
A user should be able to re-upload a file when doing edits to a judgment if they have uploaded the wrong file for instance.

**Comment by longhotsummer** [comment]
What prevents this at the moment?

**Comment by longhotsummer** [comment]
The permission which (in theory) controls this is `can delete source file`

![image](https://github.com/laws-africa/peachjam/assets/4178542/10b8a553-ce66-416e-9ca5-e87b1f2a19c6)

Can you confirm which lii this is and the perms of the individual in question?
