### ISSUE TITLE
Performance: pro-actively convert documents to PDF

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#1224]
When a crawler is indexing our sites, we get a lot of requests to convert DOCX files to PDF files.

* this puts heavy load on the server
* it repeats work unnecessarily
* in some cases soffice hangs and pegs the CPU for 30 minutes before the task is aborted

It would  be better if we pro-actively created a PDF when a document is first uploaded, so that we do it once and can manage the impact of long-running tasks that fail more easily.

**Comment by longhotsummer** [comment]
# Proposal

Conceptually, instead of converting non-PDF source files to PDF on the fly like we do now, we'll setup a background task to convert to PDF when the source file is created or changed.

## Backend

### Storing the file

* add a new `file_as_pdf` field to the existing `SourceFile` model
* the new field will hold the PDF version of non-PDF source files
* a source file that is already a PDF will not populate this field, and the existing `file` field will be used instead
* the views that use the existing `as_pdf()` method must change to use `file_as_pdf` instead. If that is `None`, return None (ie. don't generate a PDF on the fly)

### Creating/updating the file

A background task to convert from the source file to the PDF must be created (ONLY for non-PDF source files) when the file is created or changed.

**Created:** this should only be done if the source file isn't a PDF. Perhaps a helper method like `SourceFile.ensure_file_as_pdf(self)` which checks the conditions and queues up the background task if necessary

**Changed:** if the source file is changed, the existing PDF must be cleared immediately and a background task set up (similar to the above). This prevents us from serving an out of date PDF, particularly if there are issues creating the PDF from the new source file.
 
While the model does know when it's being created (or we can use a signal), the model doesn't have enough scope to know when its data has changed. Instead, the `admin.SourceFileForm._save_m2m()` method will be updated to check if the file has changed. This is similar to how we already determine when to re-extract content from a changed source file.

### The background task

The background task should first check if the source file already has a PDF version, and do nothing if it does (to make the task idempotent).

Otherwise, it can use the `as_pdf()` method to generate a PDF and store it in the new `file_as_pdf` field.

We know there are certain docx files that hang soffice and cannot be converted to a PDF. I think the timeout on soffice is currently around 30 minutes which is too high -- it will prevent background tasks from running for too long. We should reduce this timeout to, say, 10 minutes and monitor the impact.

Another benefit of the background tasks is that we'll get Sentry errors for documents that can't be converted.

## Frontend 

* no changes

**Comment by actlikewill** [comment]
@longhotsummer Looks okay. I like that it will have no changes on the frontend since we already have the pdf url.

**Comment by longhotsummer** [comment]
Backfilling-data:

* we will need to kick off a background task to backfill PDFs for all our documents. I suggest an admin action for all documents that does this, similar to what we already have.
