### ISSUE TITLE
Chore: when ingesting from Indigo, use the "type_name" field in the case where the subtype doesn't exist as a DocumentNature

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#1226]
Currently we have document natures such as "Gn" and "Genn" through documents that have been imported from Indigo.

We should be using the `type_name` field when importing a document and the subtype doesn't exist as a `DocumentNature` yet.

See https://github.com/laws-africa/peachjam/blob/main/peachjam/adapters/adapters.py#L198

Example:

```json
{
  "url": "https://api.laws.africa/v2/akn/na/act/gn/2008/266/eng@2008-11-03",
  "title": "Commencement of the Children Status Act, 2006",
  "country": "na",
  "locality": null,
  "nature": "act",
  "subtype": "gn",
  "year": "2008",
  "number": "266",
  "frbr_uri": "/akn/na/act/gn/2008/266",
  "expression_frbr_uri": "/akn/na/act/gn/2008/266/eng@2008-11-03",
  "type_name": "Government Notice",
}
```

**Comment by longhotsummer** [comment]
This will solve problems like this:

![image](https://github.com/laws-africa/peachjam/assets/4178542/6bf295ed-6f9a-4e26-9bc3-390619847ea4)


and search experiences like this:

![image](https://github.com/laws-africa/peachjam/assets/4178542/9bb90db3-ead3-4aa3-83be-72971d52d62d)

**Comment by actlikewill** [comment]
@niiroobiro We need to manually update the document natures as a follow up to this task.
