### ISSUE TITLE
As a reader I'd like to know when a judgment has been overturned by a higher court

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#1245]

**Comment by longhotsummer** [comment]
This can be set up with a work-level relationship. Currently this is pretty confusing for editors, so we should make it clearer.

**Comment by longhotsummer** [comment]
## Proposal

This is largely UI-driven, since we already have relationships. We can add a new predicate for "overturns" / "is overturned by".

The general idea:

* add a new tab to the judgment admin view for "Related judgments"
* let the user choose judgments that are overturned by this one
* use [django-autocomplete-light](https://django-autocomplete-light.readthedocs.io/) to provide auto-complete for choosing works, since it's a huge list otherwise

We'll have to see the simplest way to get the Django admin to help us to do this, since relationships are through the work, not the document.

**Comment by longhotsummer** [comment]
To finalise this, we need to include documentation on it for the editors, and ensure that all sites has predicates for:

* overturned
* upheld

**Comment by nickmwangemi** [comment]
@longhotsummer The documentation for this goes into the LII user guide, right?

**Comment by longhotsummer** [comment]
> @longhotsummer The documentation for this goes into the LII user guide, right?

No, the LII Editors guide. @niiroobiro can point to where.

**Comment by nickmwangemi** [comment]
Documentation is available at https://app.gitbook.com/o/-LoitctXFtxngZR4OieO/s/wzI8RYmmnR1XUtkKp8SY/judgments/overturned-and-upheld
