### ISSUE TITLE
Chore: enable pagerank across all sites

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#1256]
- [x] africanlii - 461
- [x] eswatinilii 2517  
- [x] ghalii - 0
- [x] lawlibrary
- [x] lesotholii - 517
- [x] malawilii - 82 
- [x] namiblii - 10282
- [x] senlii - 0
- [x] seylii - 701
- [x] sierralii - 0
- [x] tanzlii - 3651
- [x] tcilii - 2
- [x] ulii - 1888
- [x] zambialii - 532
- [x] zanzibarlii - 59
- [x] zimlii - 727

**Comment by actlikewill** [comment]
Tanzlii - Labor Relations Act - most cited but does not appear on first page
