### ISSUE TITLE
As an AfricanLII user I'd like to know that a LII for an AU Member State exists

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#1257]
In the Member States listing page (and detail page), it would be useful to provide a link to the LII.

**Comment by longhotsummer** [comment]
AfricanLII has an dict internally that lists all the LIIs, which are used on the homepage. This could be incorporated into the listing pretty easily based on country codes.

It's then a matter of layout.

**Comment by nickmwangemi** [comment]
# Proposal

We are looking to tweak the member state listing into cards which then feature the LII name and URL, for member states that have this.

![image](https://github.com/laws-africa/peachjam/assets/15012985/2092c30a-788e-47a5-8c51-4eb1c05359b1)
