### ISSUE TITLE
As a user, I shouldn't be able to see the authors I have added on a LII appearing on the AfricanLII site under regional bodies when I do a search.

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1260]
Authors who have been created on the LIIs are appearing under regional bodies.
This is a good example:
`https://seylii.org/admin/peachjam/author/7/change/#general-tab`
When a user does a search on `africanlii.org`, that has any relation to that specific author, the author's name appears under regional bodies:
`https://africanlii.org/search/?q=Report+of+the+Chairperson+of+the+Commission+on+the+Situation+in+the+Comoros&authors=Dr+Mathilda+Twomey`

**Comment by longhotsummer** [comment]
The key issue here is the label of "Regional bodies". We use the same for field for individuals and for the regional bodies.

**Comment by longhotsummer** [comment]
As a short-term solution, we are going to change the label to "Regional Body / Author" in AfricanLII.

Later we will do the work to adjust modelling to treat these two concepts are separate things.
