### ISSUE TITLE
As a TanzLII user, I want to see a different banner on the TanzLII homepage  so that we are differentiated from other LIIs

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1265]

**Comment by niiroobiro** [comment]
![Image](https://github.com/laws-africa/peachjam/assets/57619722/58a6f33e-3aa9-4e42-9f96-e334b18f0623)

**Comment by actlikewill** [comment]
@niiroobiro  The image does not contrast well with the text:

![image](https://github.com/laws-africa/peachjam/assets/25079238/55feffd0-46fc-4382-b0b0-31eeb61325e5)
