### ISSUE TITLE
Dead links on provincial high courts caselaw on LawLibrary

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#1270]
See paragraph 25 of this judgment: https://lawlibrary.org.za/akn/za-wc/judgment/zawchc/2023/35/eng@2023-04-17
The automated link dead-ends because it tries to find the judgment on https://lawlibrary.org.za/akn/za/judgment/zakzdhc/2023/7
but it is on https://lawlibrary.org.za/akn/za-kzn/judgment/zakzdhc/2023/7/eng@2023-02-20

The Editors capture locality Kwa Zulu natal, which adds to the FRBR URI.  This is being done for all provinces across the collection. 
This adjustment needs to be reflected in the regex that extracts the links.

**Comment by longhotsummer** [comment]
Interesting. We will need to update citation extractor to make it aware of provinces in certain cases.
