### ISSUE TITLE
Change the default language of uploading documents on TanzLII to English

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#1275]
Feedback
Pia kile kipengele cha Language wakati unaupload Case kwa sasa kipo katika Kiswahili by default, so ukijisahau kubadilisha wakati unapandisha shauri language inabaki ni Kiswahili
kwa kuwa kesi nyingi zipo katika lugha ya English basi default language iwe English ili hata ikitokea umejisahau ijipe yenyewe juu kwa ju

![image](https://github.com/laws-africa/peachjam/assets/46931873/42c15107-66dc-4642-9a9e-da6d575ca697)

**Comment by longhotsummer** [comment]
This is done now that the default site language is back to English.
