### ISSUE TITLE
As a SierraLII user, I want to be able to attach pdf files of the articles I am uploading to ensure they can be downloaded.

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1277]

**Comment by actlikewill** [comment]
## Proposal

### Model
- Add an ArticleAttachmentModel. We can subclass the AttachmentAbstractModel, which contains the necessary fields for and logic for saving files. Add the following fields:
  - SAVE_FOLDER = "articles"
  - document = ForeignKey to Article Model

### Download Link
- We need to add a Attachment Download link to the Article Detail template.
- A similar pattern is used for attached files in the document detail page [here](https://github.com/laws-africa/peachjam/blob/829a8612d2f07efb9165af27ce52f993b832d22b/peachjam/templates/peachjam/layouts/document_detail.html#L329-L337). i.e loop through all attachments provide a download link from the file url and show the file extension and file size.

**Comment by longhotsummer** [comment]
Sounds good.
