### ISSUE TITLE
Sometimes content on AfricanLII redirects to agp.africanlii.org

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#1289]
Ensure that all content accessed to the admin site, search and automated links points to africanlii.org instead of agp.africanlii.org

**Comment by longhotsummer** [comment]
Part of this is fixing Django's site object, which I've shown @niiroobiro how to do.

Another part is redirecting agp.africanlii.org to the africanlii.org, done in #1250

The last part is updating https://github.com/laws-africa/peachjam/blob/9977c39475a2025ac7275851de890e914830f195/peachjam/views/documents.py#L19 to redirect correctly

**Comment by longhotsummer** [comment]
Done
