### ISSUE TITLE
As an advanced reader I want to be able to choose historical versions of a document

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#129]
Some documents are available in multiple versions (dates).

In the metadata block, add an option that (a) helps the user realise there are multiple dates, (b) is clear which one they're looking at, and (c) provides links to open alternate date versions.

Perhaps the simplest is to make the current date in the `Date: xxx` metadata block a bootstrap dropdown, that shows the alternate date versions as links.

Bear in mind that there may be multiple dates AND multiple languages. How should it be handled if there are dates that aren't available in the current language?

In time, we'll add a rich timeline for multiple date versions, but this is a quick-and-easy win for now.

**Comment by ro6ley** [comment]
> Bear in mind that there may be multiple dates AND multiple languages. How should it be handled if there are dates that aren't available in the current language?

We can only show dates that are available in the current language? i.e the date dropdown only shows dates for versions in the current language and the languages dropdown only shows languages for versions that match the current document date

**Comment by longhotsummer** [comment]
> > Bear in mind that there may be multiple dates AND multiple languages. How should it be handled if there are dates that aren't available in the current language?
> 
> We can only show dates that are available in the current language? i.e the date dropdown only shows dates for versions in the current language and the languages dropdown only shows languages for versions that match the current document date

Yes, I think that's fine for now. We can be smarter down the road. For now, the bulk of the documents we have are at one date, or we have all languages for all dates.
