### ISSUE TITLE
As a TanzLII user, I want to be able to filter judgments by month the same way I can filter by year.

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1295]

**Comment by longhotsummer** [comment]
# Proposal

I see two aspects for very large listings like this:

1. if a year is selected, then add months beneath the year navigation. Those would have new urls, such as `https://tanzlii.org/judgments/TZCA/2023/2` for Feb, etc.
2. in the listing table, if the table is currently sorted by date, then visually group the rows by month. In other words, at the start of a new month have a full row that just says "August 2023", or whatever.

**Comment by longhotsummer** [comment]
At the same time, please add some padding beneath the year nav (and the new month nav) on mobile:

![image](https://github.com/laws-africa/peachjam/assets/4178542/99cfc4c4-92fd-407e-b42c-3df668c85ffb)
