### ISSUE TITLE
Reduce unused Javascript to decrease bytes consumed by network activity as a measure to improve performance scores.

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1318]
![image](https://github.com/laws-africa/peachjam/assets/4178542/2aa29029-4a62-4100-b3ac-c5b371977b01)

**Comment by longhotsummer** [comment]
See https://github.com/laws-africa/peachjam/issues/1324 for reducing unused CSS.

**Comment by longhotsummer** [comment]
A bigger target is to reduced unused JS.

I'm going to change this issue to be about that.

**Comment by longhotsummer** [comment]
done
