### ISSUE TITLE
 Transition from using HTTP/1 to HTTP/2 protocol to enhance performance and improve the user experience.

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1319]

**Comment by longhotsummer** [comment]
We already use http 2, see the "protocol" column here: 

![image](https://github.com/laws-africa/peachjam/assets/4178542/c185020e-7cca-49f6-9fdb-13020cf6466f)


It's the twitter plugin that is misbehaving.

![image](https://github.com/laws-africa/peachjam/assets/4178542/5320d6fa-a090-4e4e-8e9d-3227e404d9bf)

**Comment by longhotsummer** [comment]
Lol. Looks like we aren't alone: https://lucaspardue.com/2021/01/04/2-meg-in-the-embed-and-the-little-tweet-said-give-over/ (that's for embedding, but I assume that's similar).
