### ISSUE TITLE
Eliminating Render Blocking Resources for Improved Website Performance.

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1320]
https://developer.chrome.com/docs/lighthouse/performance/render-blocking-resources/?utm_source=lighthouse&utm_medium=devtools#how-to-eliminate-render-blocking-stylesheets

![image](https://github.com/laws-africa/peachjam/assets/4178542/21551af9-d5eb-4d34-84e2-31daa0d8413b)

So it seems we'd need to move critical CSS out of our main CSS file.

I don't think this is worth the effort right now. This would be a significant change to how we build and use our CSS.

A different option is to make the CSS file smaller by removing unused CSS.

**Comment by longhotsummer** [comment]
I'm going to close this in favour of #1324  and https://github.com/laws-africa/peachjam/issues/1318
