### ISSUE TITLE
Styling of links hides underscores in legislation URLs

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#1356]
URL of a deeplink of a section of legislation would not translate well when pasted into a document which will be printed

![image](https://github.com/laws-africa/peachjam/assets/46931873/039ce7aa-5308-43b7-b44c-2cc2e4b9586c)

**Comment by longhotsummer** [comment]
The underscores are part of the AKN standard, and the underlines are determined by the formatting in the document where it's being posted.
