### ISSUE TITLE
Link the different language versions of the platform walkthrough video on AfricanLII site.

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1358]
`https://drive.google.com/drive/folders/1Jo6rlzGNgLlE7xr4thm2OFlB41BY8xgF`
The videos have been uploaded on youtube and here are the links:
French version: `https://youtu.be/BMN38Hvt6Uw`
Swahili version:`https://youtu.be/CbtPXhdTZyA`

**Comment by longhotsummer** [comment]
Let's set it up so that the video chosen is based on the user's preferred site language, falling back to English if one isn't available.
