### ISSUE TITLE
SeyLII: Add a Donate Now  Button on SeyLII homepage that redirects a user to a page with information on how to make donations to the organization.

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1359]
**The SeyLII team is requesting for a donate button on their homepage instead of a banner that when clicked takes users to a donate page with the following text:**
Donate to the Seychelles Legal Information Institute (SEYLII) and support our work to providing free and anonymous access to case law, legislation and secondary legal materials from the Seychelles. SeyLII is an independent, self-funded organisation and needs your support. Your contribution will make a real difference and help us bring to life various of our projects for 2022-2025. (Link to our strategic plan)

 

If you would like to make a cash donation please see our banking details below:

 

Account name: SEYLII ASSOCIATION OF SEYCHELLES

Bank name: The Mauritius Commercial Bank (Seychelles) Ltd

Bank Address: P.O Box 122 - Main Branch, Caravelle House, Manglier Street, Victoria, Mahe, Republic of Seychelles +2 48 428 4555 F: +248 432 2676

Account number: 00000426814

BRN: A431282

SWIFT: MCBLSCSC

 

If you wish to donate to a specific project, to donate in kind or to learn how you may assist us in other ways please do not hesitate to contact us via email on `info@seylii.org `for more information.

**Comment by longhotsummer** [comment]
# Proposal

On the homepage, between the search box and the logos, add a new section:

**Donate to SeyLII.** SeyLII is an independent, self-funded organisation and needs your support.

Put a primary "Donate to SeyLII" button to the right of that text.

Add a new `/donate` page that has the information included above.



Later, we will make this self-configurable.

**Comment by actlikewill** [comment]
@niiroobiro The text says (Link to stategic plan) do you have the link?

**Comment by niiroobiro** [comment]
@actlikewill 
Here you go.
`https://seylii.org/akn/sc/doc/strategic-plan/2022-10-31/seylii-strategic-plan/eng@2022-10-31`
