### ISSUE TITLE
Generated judgment titles must be sensitive of missing case details like numbers

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#1373]
eg. https://tanzlii.org/akn/tz/judgment/tzhc/2023/18850/eng@2023-07-12

```
Saleh Thuwel Ahmed vs Tunduru District Council and Another (Misc Civil Application None of None) [2023] TZHC 18850 (12 July 2023)
```

The `None` in the case number part of the title should be handled better.

**Comment by nickmwangemi** [comment]
@longhotsummer Is there a case whereby we have number and not the year or the year and vice versa?

**Comment by longhotsummer** [comment]
This depends entirely on what the editor uploading the judgment tries to do. In general, a case should have both a number and a year.

I suspect that when one is missing, it's actually a mistake 99% of the time. There may be rare cases where one piece of info is missing.

One option is to make those fields required in the admin area. However, since this information is not essential, it seems a bit obtuse to force that (there are those inevitable edge cases where only partial info is available, and is better than no info).

So I suggest we tolerate that and simple accommodate it when generating the case number string so that it looks a bit better than "None".  Perhaps "(unknown)"?
