### ISSUE TITLE
As a judgments editor, I would like access to only relevant tabs in the judgment form

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#1431]
and in order that facilitates my workflow that follows the reading of the judgment cover page

Remove the following tabs from the editorial view
![image](https://github.com/laws-africa/peachjam/assets/46931873/eb7e2de5-bc84-4c6f-ba94-2fb272f15005)

Leaving only the following tabs, arranged in the order specified in the screenshot below. Then change the labels of some of the items under each of the below specified tabs
![image](https://github.com/laws-africa/peachjam/assets/46931873/4ee8dff0-d5bf-40b5-ae5f-f45d3f89604a)

**Comment by longhotsummer** [comment]
The `additional_citations` field can be removed completely, it is no longer needed as the Alternative Names field handles that functionality.

**Comment by longhotsummer** [comment]
The peachjam settings model controls which countries are available in the dropdown -- if there is one, default the country value for a new document form to that value (ie. if there's one country, select it automatically) -- this is similar to how we default the language

Mariya would like the "work identification" and "advanced" tabs removed. They are both useful for admins -- in particular, the Advanced tab allows an advanced editor to prevent a result from showing up in a search result. So what we really need is to only show them to users with an appropriate permission. I suggest a new permission on CoreDocument called something like `can_edit_advanced_fields` and base the display of those tabs on that permission.

**Comment by longhotsummer** [comment]
It looks like we can configure the order of tabs/fieldsets using `jazzmin_section_order` somehow: https://github.com/farridav/django-jazzmin/blob/master/jazzmin/templatetags/jazzmin.py#L341

**Comment by nickmwangemi** [comment]
Partially resolved by #1480
