### ISSUE TITLE
Add links to the  help pages on Admin pages of the site.

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1449]

**Comment by longhotsummer** [comment]
# Proposal

Admin/editor documentation is at https://liieditors.docs.laws.africa/

1. add `https://liieditors.docs.laws.africa/` as a settings.py setting and ensure it's injected into templates via the context processor - see https://github.com/laws-africa/peachjam/pull/1430
2. add a field to the ModelAdmin classes in `admin.py`, something like `help_topic` = `judgments/upload-a-judgment`
3. extend https://github.com/farridav/django-jazzmin/blob/master/jazzmin/templates/admin/change_form.html#L99 to override `extra_actions` and add a help button if `help_topic` is there.
