### ISSUE TITLE
As an admin, I want to be able to allow a legislation listing page to have an entity profile

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#1461]
This will allow admins to add partner logos and attribution on legislation listing pages.

This is required for LesothoLII.

## Proposal

* For `/legislation/<code>` (locality legislation listing page), load and render the entity profile for the locality
* For `/legislation`, we need to know which country to load an entity profile for. The simplest is to check if `peachjam_settings.document_jurisdictions` has a single country. If it does, load and render the locality for that jurisdiction.

This means for sites that cover multiple countries (only africanlii.org), we won't show an entity profile for the legislation page. That's fine for now, since AfricanLII.org doesn't have that page.

**Comment by nickmwangemi** [comment]
@longhotsummer Since a country may hold multiple localities, how about we introduce a new model to hold a country's profile?

**Comment by longhotsummer** [comment]
I think we'll need to, because there is no other way to associate an EntityProfile with a Country object, because the Country model is from countries_plus, right?

**Comment by nickmwangemi** [comment]
> I think we'll need to, because there is no other way to associate an EntityProfile with a Country object, because the Country model is from countries_plus, right?

Yes, it's from the 3rd party package
