### ISSUE TITLE
As a user of a LII website, I would like to filter my search results by Reported cases only

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#1462]
Offer the user a filter option for only Reported cases. Suggested this be placed above the search results and not in the left sidebar, so users can switch on and off the reported cases results
![image](https://github.com/laws-africa/peachjam/assets/46931873/442f4ed0-8989-4393-9c13-e2ed8f19d1c8)

**Comment by longhotsummer** [comment]
We can easily add a facet for labels on the left.

 > Suggested this be placed above the search results and not in the left sidebar, so users can switch on and off the reported cases results

I think we should do this more generally. When a facet is toggled on, add it as a clickable "bade" along the top of the search results, and remove it if the user clicks on it. This will make it clearer what filters are applied, particularly when the search page is loaded from another page and already has filters applied.
