### ISSUE TITLE
As a legislation user I want a warning when I'm reading legislation that is commenced, but only at a future date.

### ISSUE THREAD

**Issue by goose-life** [laws-africa/peachjam#1464]
e.g. https://lawlibrary.org.za/akn/za-eth/act/by-law/2023/water/eng@2023-08-10
comes into force on 2024-02-10

**Comment by goose-life** [comment]
cf https://github.com/laws-africa/peachjam/issues/274

**Comment by longhotsummer** [comment]
The current banner is only for `commenced=False`. In this case, it's about `commenced=True` but the commencement date is in the future.
