### ISSUE TITLE
Brand OpenLawAfrica sites appropriately, starting with AfricanLII

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#1482]
Include the OpenLawAfrica horizontal logo on AfricanLII in the top black ribbon and link the website: https://www.openlawafrica.org/ 

Other OpenLawAfrica sites are:
1. LawLibrary
2. TanzLII
3. ULII
4. GhaLII
5. SeyLII

**Comment by longhotsummer** [comment]
Here are the logos, one for a black background (the suggested) and one for a pale background (in case the black doesn't work):

* normal: ![Open Law Africa- Rectangular Submark](https://github.com/laws-africa/peachjam/assets/4178542/6058a496-454c-4803-853a-23cfebb599f8)
* inverted:  ![Open Law Africa- Logo Invert Colour-19](https://github.com/laws-africa/peachjam/assets/4178542/1107a1b7-0991-477a-9893-ab3dca79e8e4)
