### ISSUE TITLE
As a legislation user I want to see the disclaimer on a stub, too

### ISSUE THREAD

**Issue by goose-life** [laws-africa/peachjam#1502]
Here is a stub on edit.laws.africa: https://edit.laws.africa/works/akn/mw/act/gn/1963/283/
It includes a disclaimer, "The publication date of this work could not be ascertained. We used the date 31 December 1963 because the work was published during the course of the year 1963."

Here is the same Act on MalawiLii: https://malawilii.org/akn/mw/act/gn/1963/283/eng@1963-12-31
The content hasn't been marked up, so we're displaying the source PDF, which means there's no generated coverpage, and therefore the disclaimer isn't showing anywhere.

**Comment by longhotsummer** [comment]
@goose-life can you check what's available from the API that would allow us to craft a better message on the peachjam sites?

**Comment by goose-life** [comment]
The disclaimer is not included in the serialized work at all — see 

https://github.com/laws-africa/indigo/blob/master/indigo_content_api/v2/serializers.py#L102

and 

https://github.com/laws-africa/indigo-signoff/blob/master/indigo_signoff/serializers.py#L73

**Comment by actlikewill** [comment]
@goose-life @longhotsummer With the disclaimer added whats a good place to show the disclaimer? add a new tab?

**Comment by goose-life** [comment]
I was picturing it as part of these pieces of metadata at the top: 
<img width="525" alt="image" src="https://github.com/laws-africa/peachjam/assets/32566441/75697eaa-9b10-42c0-920a-05bdfd183a1a">

Maybe after 'Date'?
