### ISSUE TITLE
Add links to the help user guides

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1534]
The following help guides are ready:

1. Federated case indexes on AfricanLII
2. Federated Search on AfricanLII
3. Pocket Law
4. African union documents

**Comment by actlikewill** [comment]
@niiroobiro @longhotsummer Whats the best place to put each these links?

**Comment by niiroobiro** [comment]
![Image](https://github.com/laws-africa/peachjam/assets/57619722/74149219-7225-4fb4-af09-558254589ea8)



![Image](https://github.com/laws-africa/peachjam/assets/57619722/7064d085-96b1-4fbd-8061-a2770f71c304)




![Image](https://github.com/laws-africa/peachjam/assets/57619722/5257562d-e23a-40e0-afae-97c30648a802)



![Image](https://github.com/laws-africa/peachjam/assets/57619722/bdf0c2c9-0ea6-4fed-ba88-282649b7dbf6)

@longhotsummer Is this okay?
