### ISSUE TITLE
As a reader of a generic document, I would like to be able to download the original PDF of a publication

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#1540]
https://zambialii.org/akn/zm/doc/book/2023-09-20/legal-media-handbook-for-zambia/eng@2023-09-18

A PDF produced for distribution as a PDF, not the one generated from the Word file uploaded to create the web page version

**Comment by longhotsummer** [comment]
There are two options here:

1. upload the word document so that there's a rich HTML experience, delete that source file and replace it with the PDF
2. upload the PDF as an alternative attachment
