### ISSUE TITLE
As a legislation user, I want to understand why content of a work is blank

### ISSUE THREAD

**Issue by goose-life** [laws-africa/peachjam#1581]
see for example https://tanzlii.org/akn/tz/act/1972/1/eng@1972-03-01
It's a pure stub, without a publication document, so there's no PDF loaded where the content will eventually go.
At some point, a consolidation will be imported and signed off, and then there will be a point in time at 2002-07-31.
But for now, it looks as if the content is missing.

### Approach 1
Add a notice to the page that reads something along the lines of 'There is no content available for this {friendly type} yet; it will be updated in due course.'
- pro: our intention of not hiding what we know from users (even if it's incomplete), while communicating shortfalls, is met
- con: does this erode trust, if only some of our works are useful in terms of showing what the content is?

### Approach 2
Don't allow stubs to be signed off without publication documents from edit.laws.africa — open a separate issue for that, and delete all existing WorkExpression objects that don't meet the minimum criteria of either at least one point in time or a publication document.
- pro: avoid embarrassment if an Act takes a while to import for whatever reason
- con: we're locking away our knowledge of the existence of the Act until we have the content

@longhotsummer @NotoriousMBB thoughts on which approach to take? I'm honestly not sure if it's better to list a bunch of Acts for a place, but only some of them have content available, or to only list Acts for which we have content. I'm kindof leaning towards Approach 2, but I might be missing something in the value of having a fuller listing of Acts for a place, content aside.

**Comment by longhotsummer** [comment]
Another option is for peachjam to ignore documents that are empty AND don't have a publication document.

**Comment by NotoriousMBB** [comment]
Simplest, and make sure it automatically picks it up when content is
imported. I,e how does it treat the sign off flag (improvising here)

**Comment by goose-life** [comment]
closed by #1584
