### ISSUE TITLE
Recent legislation list on home page is acting weirdly

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#1633]
I propose that the recent legislation list on the home page of LII lists the most recent legislation by commencement added on the website. For example on home page of tanzlii.org the most recent legislation listed is from 2022, while the All legislation tab shows us that there are 25 pieces of legislation from 2023 on the site

https://tanzlii.org/legislation/all

**Comment by longhotsummer** [comment]
In theory, we should be choosing recently legislation based on the `date` field, which should be sufficient to show the most recently promulgated legislation.

**Comment by longhotsummer** [comment]
We do this, which looks correct:

```
context["recent_legislation"] = Legislation.objects.filter(
            metadata_json__stub=False
        ).order_by("-date")[:10]
```

https://github.com/laws-africa/peachjam/blob/main/liiweb/views/general.py#L14

Perhaps we need to remove the filter on `stub`.
