### ISSUE TITLE
As an editor I want it to be easy to ensure that a judgment's place/locality is correct for the linked court

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#1640]
We have a number of cases in ZA where the wrong locality is chosen for a court. eg. for a Gauteng-based judgment + court, sometimes the locality is None, sometimes GP, sometimes JHB. The correct value is GP.

We can optionally link a country (+locality?) to a court. Then, if a user links that court to a judgment, it either shows an error if the places don’t align, or it forces the place on the judgment to the court’s place. That will make it harder to get it wrong.

**Comment by longhotsummer** [comment]
I don't think an error is useful - the system knows what the place/locality should be - it seems obtuse to tell the user to set it like that. Just set it directly in the judgment model's `.save()` method.

**Comment by nickmwangemi** [comment]
@longhotsummer That means we introduce a locality field on the court model which we can then enforce on the judgment upon saving?

**Comment by longhotsummer** [comment]
Yes. Let's link both a country and a locality (both optional).
