### ISSUE TITLE
As a search user I want to go beyond page 8 of paginated search results

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#1651]
I cannot go past page 8 of the search results here, even though there are 1200+ filtered search results

https://tanzlii.org/search/?q=%22Commission+for+Mediation+and+Arbitration%22&page=8&doc_type=Judgment&court=High+Court+Labour+Division

**Comment by Sandravaphilips** [comment]
@longhotsummer It looks like the _maxPages_ for pagination was deliberately set to 8. Would you like me to increase the number or remove the limit on pagination? https://github.com/laws-africa/peachjam/blob/ce690d2099bab7fcaf1f3e3eba823cb97a221f17/peachjam/js/components/FindDocuments/SearchPagination.vue#L21

**Comment by longhotsummer** [comment]
Yes - perhaps 15 pages?

The trouble is on mobile, the paginator would grow beyond the size of the browser. Any simple solutions? Maybe overflow-x: auto on the paginator?
