### ISSUE TITLE
As a user, I'm frustrated that so many PDF judgments require me to click a button before displaying

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#1656]
![image](https://github.com/laws-africa/peachjam/assets/46931873/bf2e3771-6717-4bd5-8669-041ac090f1a1)

**Comment by longhotsummer** [comment]
Let's bump the cut-off to 10MB.

**Comment by longhotsummer** [comment]
See https://github.com/laws-africa/peachjam/blob/be42f13eea33afe6c9aae8d168b8d1fce192bb5d/peachjam/templates/peachjam/_document_content.html#L85
