### ISSUE TITLE
Logos on eSwatiniLII home page are too large on Chrome

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#1657]
![image](https://github.com/laws-africa/peachjam/assets/46931873/38cbd949-3695-47a9-9d33-087cbf8f379d)

**Comment by nickmwangemi** [comment]
@longhotsummer Would it make sense to remove the logos at that point since they are already available as hero logos?

**Comment by longhotsummer** [comment]
yes, i'm not sure why they're there, the other sites don't have them in the right column
