### ISSUE TITLE
When a document with a relationship is deleted, the work and the relationship remain which is confusing

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#1658]
eg. https://lawlibrary.org.za/akn/za/judgment/zast/2022/32/eng@2022-06-09

![image](https://github.com/laws-africa/peachjam/assets/4178542/dd33f574-3d56-4b9d-af65-657eec683bf9)

The case summary document has been deleted, but the relationship remains, which means that following that link goes to a 404 page.

**Comment by nickmwangemi** [comment]
@longhotsummer Do we delete the corresponding work and relationship objects or just filter them from the related documents list?
