### ISSUE TITLE
As an editor, for analytics purposes, i.e. not public, I would like to capture in metadata the name of the judge in the lower court judgment

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#1666]
So, this would create two categories of judges associated with a judgment 
- judges who have written and signed the current judgment document
- judge(s) who wrote the judgment that is being appealed or overturned

**Comment by NotoriousMBB** [comment]
@niiroobiro Here is the write-up on this issue: https://docs.google.com/document/d/1xqjEXYH6uTTjchoVi_KD9yBQ3XqKKKepmv4eV2sAHB0/edit?usp=sharing

**Comment by longhotsummer** [comment]
Add a new "lower court judges" field, many-to-many.
