### ISSUE TITLE
Change links to social media profiles on LawLibrary home page

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#1682]
Change the lawlibrary.org.za social media accounts on the front page to 

FB: **https://www.facebook.com/lawlibraryZA**
X: @lawlibraryZA
LinkedIn:  **https://www.linkedin.com/company/101482949**
![image](https://github.com/laws-africa/peachjam/assets/46931873/bc688ac9-eef0-4d72-86ab-cecf75cbdab6)

**Comment by nickmwangemi** [comment]
@niiroobiro We can change the Facebook and X links in the site settings. As for LinkedIn, we'll have to add a new field for it.

**Comment by longhotsummer** [comment]
@nickmwangemi pls can you add support for LinkedIn.

@niiroobiro pls change the links in the settings page.
