### ISSUE TITLE
As a User, I want to be able to save documents I find interesting on the site.

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1690]

**Comment by niiroobiro** [comment]
Here is the link to the proposal:
`https://docs.google.com/document/d/1UHUXtD5lUf9TCMibt0pgv1BFPIeDQixOEPmJDgfZQbg/edit?usp=sharing`

**Comment by niiroobiro** [comment]
@longhotsummer I have made edits to the feature proposal. Let me know if it still needs some more work.

**Comment by longhotsummer** [comment]
This is ready to implement.
