### ISSUE TITLE
As an editor uploading judgments, I want to see the correct document when I make edits to a file.

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1737]
Editors occasionally need to replace the initially uploaded version of judgment with an alternative version. The reason is that the first copy that is sent is a video graphic version and the second is usually the correct one. Most of the time, the editors find that they have already uploaded the first version and need to change that.

**User needs Description:**

The updated file does not appear on the site after replacing the original file, even though it shows as changed in the source files.
When an editor clicks view on the site, you still view the original file instead of the replaced copy.

**Conclusion:**

I believe what’s happening from the two examples below is that an editor will replace a file and when the change is not reflected on the site, they will delete the file altogether because it’s better to have no document than a wrong one. That’s why most users find no pdf /pdf downloads on the site.

**Examples of such judgments:**

https://tanzlii.org/akn/tz/judgment/tzhc/1981/1/eng@1981-12-03
https://tanzlii.org/akn/tz/judgment/tzhc/2023/23435/eng@2023-12-15

**Comment by niiroobiro** [comment]
@longhotsummer We have determined that the source file is not updated immediately because of caching which is 24 hours according to @actlikewill. Can we reduce the time the files are updated?
Another issue that might be a bug is, replacing docx files with pdfs.
When we clear the content HTML the PDF file is not visible. The page is empty. We realized that an editor has to go back and clear the contents in the source tab. Do you think this can be done automatically?

**Comment by longhotsummer** [comment]
> Another issue that might be a bug is, replacing docx files with pdfs.
> When we clear the content HTML the PDF file is not visible. The page is empty. We realized that an editor has to go back and clear the contents in the source tab. Do you think this can be done automatically?

@actlikewill is fixing this now

**Comment by longhotsummer** [comment]
> We have determined that the source file is not updated immediately because of caching which is 24 hours according to @actlikewill. Can we reduce the time the files are updated?

I suggest we reduce this to the 30 minutes that general pages on the site are cached *AND* disable it for staff users, which also matches the logic for the site-wide cache.

This will mean that editors/uploaders immediately see the changes, and general users will pick up the change after at most 30 minutes.

**Comment by longhotsummer** [comment]
> > We have determined that the source file is not updated immediately because of caching which is 24 hours according to @actlikewill. Can we reduce the time the files are updated?
> 
> I suggest we reduce this to the 30 minutes that general pages on the site are cached _AND_ disable it for staff users, which also matches the logic for the site-wide cache.
> 
> This will mean that editors/uploaders immediately see the changes, and general users will pick up the change after at most 30 minutes.

I *think* we can do this by simply removing the explicit caching provided for here https://github.com/laws-africa/peachjam/blob/main/peachjam/urls.py#L164 and just letting the [GeneralUpdateCacheMiddleware](https://github.com/laws-africa/peachjam/blob/main/peachjam/middleware.py#L51) work its magic.

**Comment by actlikewill** [comment]
> > Another issue that might be a bug is, replacing docx files with pdfs.
> > When we clear the content HTML the PDF file is not visible. The page is empty. We realized that an editor has to go back and clear the contents in the source tab. Do you think this can be done automatically?
> 
> @actlikewill is fixing this now

@longhotsummer this is slightly different. When a docx is replaced with a pdf, there is usually some content html. The site will still show the content html since it is the priority. If the user clears the content html, there is still some place holder content html left in the ckeditor source tab which means the user now will see a blank page until they clear all the content html from the ckeditor source tab
