### ISSUE TITLE
Search: index AKN document provisions separately; boost title matches; show in results

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#1759]
We can do a much better job of showing provision-based results for AKN documents.

* match on titles and provision content
* boost title matches
* show TOC hierarchy when showing a provision match
* make the TOC items clickable

**Comment by longhotsummer** [comment]
# Problem

Consider a search like "children court attendance". On LawLibrary.org.za, we have results like this (note the scores):

![image](https://github.com/laws-africa/peachjam/assets/4178542/3cd9abcc-069e-4c5e-aa55-3c46154528f6)

After the first three matches, the scores drop drastically (below 40). The Children's Act is not in the first page of results, even when the search is restricted to legislation. This is despite the fact that there is a section related to this:  

![image](https://github.com/laws-africa/peachjam/assets/4178542/be4b61cc-3a8f-4f00-9492-fe663ef9c957)

The part of the problem is that headings are treated as regular text when indexing AKN documents. We can do better.

# Proposal

The idea is to take advantage of the AKN Table of Contents (TOC) and use that in smart ways, in particular:

1. apply search terms to the TOC when searching
2. display the TOC to provide context for legislation search result snippets
3. make the TOC context clickable to let the user jump directly to the relevant portion of the document (like we do with page numbers in PDF results)

For example, for the search "children court attendance" you could imagine a search result like this:

```
Children's Act
  2023-11-08 Legislation
  Act 38 of 2005
    Chapter 4 - Children's Courts
      Part 2 - Court proceedings
        56. Attendance at proceedings
          ... children's court ... attended ...
```

1. the TOC itself is searched section 56 is matched because it and its parents have a strong match to the keywords
2. the content of section 56 is also matched because it has a strong match
3. the content of section 56 is highlighted and the snippet is shown with the context of the TOC above it
4. the TOC elements are clickable, not just the Children's Act title

**Comment by longhotsummer** [comment]
# Indexing

When indexing AKN legislation content, we don't index the text as a big chunk. Instead, we drive indexing through the TOC, a bit like we do when indexing PDFs pages. So we'll index provisions instead.

1. traverse the TOC without going below `basic_unit: True`.
2. for each element in the TOC, index that as a `provision` sub-document in elasticsearch.
3. a provision is indexed with:
  * its TOC title (eg. "Part 2 - Court proceedings")
  * its provision eId (eg. `chp_4__part_2`) -- not searched
  * the in-order array of its parents' titles (this is necessary for displaying the tree in the search results)
  * the in-order array of its parents' eids (necessary for making them clickable) -- not searched
  * its text content

## Searching

When searching, the search is applied against:

* provision.title
* provision.parent_titles -- we'll need to test this; the idea is that not all keywords may be in one title, but may be spread across the path of titles 
* provision.content

TODO: how do we avoid showing both a section and its parent chapter, if  both are strong matches? do we try to avoid that?

## Rendering

Rendering is fairly simple. As part of the search results, we already return page details for matched PDF pages. For legislation, we also return provisions and include the title, eid, parent titles, and parent eids. That's sufficient to render the tree to provide context for the result snippet, without having to re-build the TOC tree.

## Outstanding

1. We must guarantee that the TOC covers all root-level elements, so that we don't skip text just because it isn't in a hierarchical container
2. we may want to do this only for certain AKN document types; eg legislation. Judgments and other non-hierarchical AKN documents won't benefit from it.

**Comment by mama-codie-T** [comment]
> TODO: how do we avoid showing both a section and its parent chapter, if both are strong matches? do we try to avoid that?

I think we should show section and parent chapter as it provides context. In the given example, user could be searching for content relating to whether children are allowed at court proceedings i.e. any court or whether the children's court requires children to be in attendance - section 56 is dealing with the latter.

**Comment by goose-life** [comment]
I agree about only doing it for legislation (at least to start).
In general it makes lots of sense and sounds like a big improvement. 
I would maybe look at all ToC elements that have headings rather than `basic_unit`, which is set per place and doesn't handle e.g. paragraphs in Schedules. 
I also agree about showing both the parent and the child as separate hits (ranked on their own strengths, with only the child taking the parent's heading into account).
