### ISSUE TITLE
Ratifications count incorrect on AfricanLII

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#1778]
When importing ratification information, we report on all 55 states. Those that have not signed and/or ratified a document, are still imported but the signature date is left blank. Yet the counter on the Ratifications tab counts each entry.

Could the counter please count only the actual Ratification Date that is not null entries?

**Comment by NotoriousMBB** [comment]
While on this,  because these instruments commence either on signature, ratification or deposit (can vary), it would be useful to count each of those events separately. This is what the AU does, see for example totals for each table column here: https://au.int/sites/default/files/treaties/37309-sl-ROAD_SAFETY_CHARTER_0.pdf

**Comment by longhotsummer** [comment]
example: https://africanlii.org/akn/aa-au/act/charter/1990/rights-and-welfare-of-the-child/eng@1990-07-01

the "Ratifications" tab count should take into account only those with `ratification_date != None`.

Additionally, put counts at the bottom of the table.

![Image](https://github.com/user-attachments/assets/ef67cd9d-16cb-42d3-b9b1-c9d0273428f2)
