### ISSUE TITLE
When searching from the listing page search box on certain pages, it should facet search results for me

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#1791]
this happens correctly on pages like https://africanlii.org/au/au-organs/ACHPR/

but not on:

* https://africanlii.org/indexes/case-indexes/case-indexes-human-rights
* https://africanlii.org/legal-instruments/

etc.

**Comment by actlikewill** [comment]
@longhotsummer for the above examples, we cannot add a preset for either. For Legalinstruments we set the document nature as the doc_type. The documents do not share a common document type eg. Activity report, Charter etc so we cannot lock the search listing to a single one. (!unless we put all of them)
For the taxonomy listing view, we don't have taxonomies in the faceted fields
