### ISSUE TITLE
Implement a listing page for adding and tracking bills on MalawiLII and ZambiaLII

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1794]
Adding bills will be as we do articles. We want to have a way for users to know they can view and track bills on the Malawi and Zambia sites.
How this should be done is something like this:

- We should rename the articles menu item at the top menu bar to read Legal Resource Center.
- Users should see the articles/bills on the landing page 
- We should have something like what we have on the AfricanLII landing page where we have different document types represented with the most recent documents and a user can view more if they want to.
- We should have 2 sections of articles. The bill tracking articles and the other articles.

![Image](https://github.com/laws-africa/peachjam/assets/57619722/2ae8649f-3cb3-48a3-9d41-1a0df49fd1e9)

- We can also have tags for the articles.

**Comment by actlikewill** [comment]
- For malawilii and zambialii
- @niiroobiro to provide where to put links

**Comment by niiroobiro** [comment]
@actlikewill add the links for bills to the header for MalawiLII and ZambiaLII
