### ISSUE TITLE
As a researcher, I want to know ratificaction and other important events in the lifecycle of treaties and other documents

### ISSUE THREAD

**Issue by ro6ley** [laws-africa/peachjam#18]

**Comment by longhotsummer** [comment]
eg. see https://twitter.com/AUABC_/status/1555144511382249472?s=20&t=G6y9Kz_6zAiv_httXkyfQg

**Comment by longhotsummer** [comment]
eg. see ratification footnote at start of this document https://agp.africanlii.org/akn/aa-au/act/1969/civil-aviation-commission/eng@1969-01-17

**Comment by longhotsummer** [comment]
Completed by ratifications.
