### ISSUE TITLE
Handle long document lists and citation lists

### ISSUE THREAD

**Issue by actlikewill** [laws-africa/peachjam#1808]
We need a better way of handling long lists of documents.

This is a problem for both long lists of citations in the document detail view and the legislation view.

We may want to split incoming and outgoing citations into separate tabs, and make them actual URLs so they are loaded separately (or via HTMX)

**Comment by longhotsummer** [comment]
eg. see the expanded citation list for https://tanzlii.org/akn/tz/act/ord/1930/11/eng@2019-11-30
