### ISSUE TITLE
As a user when downloading source file pdfs, I want to see the title of the document as the file name.

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1829]
Files downloaded have file name as source.pdf

**Comment by longhotsummer** [comment]
We already do this, we send the appropriate headers to tell the browser to use a particular filename. I've tested it for derived PDF and the original.docx



![Image](https://github.com/laws-africa/peachjam/assets/4178542/7c6fdc43-5441-4f91-ab08-6ab79a26902b)


Do you have an example of when this doesn't work? Browser, OS, etc.?

**Comment by actlikewill** [comment]
this is working as it should.
