### ISSUE TITLE
Soft launch: site footer

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#193]
* remove video
* blurb should be about laws.africa, africanlii and the CSO-AGP project (text to be provided)
* update partner list (text to be provided)

**Comment by musangowope** [comment]
Details:

- Update About AfricanLII:
AfricanLII is an open-access research platform for African law jointly operated by the AfricanLII programme of the University of Cape Town and Laws.Africa. AfricanLII publishes the law and policy of the African Union and federates search across all open access African national law available through the [Open Law Africa](https://openlawafrica.org/) community of LIIs. 

The publication of the African Union material is co-sponsored by the European Union and is part of the [Data for Governance Alliance project](https://www.afrobarometer.org/impact/informing-the-public-discourse/data-for-governance-alliance/).

- Remove video

- Under With support from  Include the  [Sigrid Rausing Trust](https://www.sigrid-rausing-trust.org/) [Indigo Trust](https://indigotrust.org.uk/)
European Union

- The updated list of LIIs to include in the last footer is the list on https://seylii.org/ - see third column in the footer.
