### ISSUE TITLE
As a user, I want the highest ranked document in search results highlighted

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1964]
The idea here is to call out the top search result when its search score is notably higher than the other results, as this indicates this is very likely the result the user is looking for.

For example, in this search, the top result is scored significantly higher than the next one:

![image](https://github.com/user-attachments/assets/acba845f-d410-4c21-9969-6cd678311481)

It's useful to call that out to the user, because they don't see internal scores.

**Comment by longhotsummer** [comment]
Perhaps something like this:


![image](https://github.com/user-attachments/assets/056a5595-5d19-4bc3-b9e6-eba9b56593e4)


on the `.card` for the best hit, add some extra css:

```
box-shadow: 0px 0px 5px 2px var(--primary)

&::before {
  content: "Best match"; // to pull in translations, perhaps set this on a data attribute and use attr(data-best-match)
  display: inline;
  position: absolute;
  right: -1px;
  bottom: -1px;
  padding: 0.25rem 0.5rem;
  border-bottom-right-radius: 6px;
  background: var(--primary);
  color: white; // NB: these two need to be set together, so perhaps this is done in SCSS
}
```
