### ISSUE TITLE
As a TanzLII user, I want to see the latest uploaded JOT documents appearing first

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#1983]
The dates on the JOT document listing page are not ordered correctly. The expectation is that documents should be sorted by the upload date, with the most recently uploaded documents appearing at the top. Currently, the dates are not sorted in a logical order, which makes it difficult for users to find the most recent documents.

![Image](https://github.com/user-attachments/assets/d9c6ecc8-668f-4550-bb13-cb3fbf2aba4b)

**Comment by niiroobiro** [comment]
@actlikewill We should check across all listing pages. Getting this request a lot.

**Comment by actlikewill** [comment]
@niiroobiro they can change the sorting themselves using the sort by drop down, but we can look into adding functionality for making it default

**Comment by niiroobiro** [comment]
Let's just make it default. Seems that functionality is lost on many users. Maybe because nothing is telling them they can do that.

**Comment by longhotsummer** [comment]
Our original default was to sort most-recent-first, which we should fall back to. Sorting alphabetically is an exception.
