### ISSUE TITLE
Make filters in listing views mobile-friendly

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#199]
The idea is to have a very similar experience to the fly-out experience we have on gazettes.africa's search.

Bootstrap 5 has an offcanvas component which should take away the bulk of the hard work here. https://getbootstrap.com/docs/5.0/components/offcanvas/

Ensure that we have the same experience for search and for listing facets.

**Comment by musangowope** [comment]
@longhotsummer I think this should be prioritised as well for the soft launch?
