### ISSUE TITLE
Changes to TanzLII

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#2018]
1. Add Finding Aids under Research Hub: https://tanzlii.org/taxonomy/finding-aids
2. On a judgment display, move the order field to the end of the display:https://tanzlii.org/akn/tz/judgment/tzca/2024/155/eng@2024-03-05
![Image](https://github.com/user-attachments/assets/a5fee3ec-e03b-43b3-9dad-1d897c60b8b2)

**Comment by actlikewill** [comment]
@longhotsummer There was a request to have better visual separation of the various blocks in this section. The request was to separate them with different backgrounds rather than using <hr/>. I'm curious on your thoughts on this

**Comment by actlikewill** [comment]
@niiroobiro for the first Finding Aids issue, that is a change to the taxonomy content and can be handled in the admin.
