### ISSUE TITLE
Lawlibrary: look and feel

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#203]
Implement a look and feel similar to lawlibrary.org.za:

* primary colours
* logo and other branding
* homepage placeholder image
* blurb on homepage
* footer
* about text

# aspects NOT to worry about (ie. keep the peachjam default)

* fonts
* text sizes
* adjustments to the navbar
* background colours (ie. keep the peachjam white)
* navbar and other dropshadow

**Comment by musangowope** [comment]
A couple of things to consider
Navbar:
What content/links are going to be on lawlibrary on the navbar? Judgements Link, National Legislation Link, Provincial Legislation Link, Search box, About Link?
- **The footer content:**
- Do we copy all the content as is, perhaps minus the video?

Body of home page:
2 column structure
- First column has Recent documents. Recent documents UI could look like agp africanlii
- second column has the about blurb + tabs (Facebook and twitter embed)
