### ISSUE TITLE
Basic User profile page

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#2035]
As a user, I want to be able to:

* see/change my account details, including name and email address
* reset my password
* manage my linked social media accounts

# Proposal

## Design

- Have a My Account link on the username dropdown.
- The profile page will look like every other page with header and footer.
- Five navigation tabs for profile, password, email addresses, social accounts, and saved documents.
- The rest of the design stays the same as indigo with minor changes.

## Implementation

- We’ll default to using all-auth URLs and views to manage passwords, email addresses, and social accounts.
- If we need to edit a template or view, we’ll include the template under accounts/ and create a view for the corresponding URL.
- The profile views will be rendered as forms that are ready to be submitted.
- We already have a layout for PeachJam, so we’ll extend that.

### URLs

- Profile view or edit - accounts/profile/
- Password edit - accounts/password/change/
- Add or remove email addresses - ​​accounts/email/
- Social accounts - accounts/social/connections/
- Saved documents - saved-documents/folders/

**Comment by longhotsummer** [comment]
In Indigo, we rely heavily on `allauth.account` to make these pages easier to do.

* We add `allauth.urls` into the urls: https://github.com/laws-africa/indigo/blob/master/indigo_app/urls.py#L18
* We add a custom EditAccountView: https://github.com/laws-africa/indigo/blob/master/indigo_app/urls.py#L19
* We override the account templates here: https://github.com/laws-africa/indigo/tree/master/indigo_app/templates/account

For all of those views, we use a standard account layout, which includes the header and side navigation. That way they have the same look and feel. 

Check the existing allauth templates to see what they look like, and then replicate them as necessary.

**Comment by Sandravaphilips** [comment]
@longhotsummer I've left a proposal in the description above. I'm ready to go if you're fine with it.

**Comment by longhotsummer** [comment]
Looks great, thanks @Sandravaphilips
