### ISSUE TITLE
Add OAG branding to TanzLII

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#2102]
Two outstanding areas for OAG branding

add logo of OAG here
![image](https://github.com/user-attachments/assets/8f7816f4-81fd-4104-87da-4b32f92ded25)

and in the footer - link to OAG website. 

![image](https://github.com/user-attachments/assets/343f759e-6fa1-43d6-af5c-867a65c907bf)

Also change the blurb to
TanzLII is operated by the Judiciary of Tanzania and the Office of the Attorney General, Chief Parliamentary Draftsman, and publishes the law of Tanzania for free online access for all. Free Access to the law supports the rule of law and access to justice. TanzLII partners with [African Legal Information Institute](https://africanlii.org/) (AfricanLII) and [Laws.Africa](https://laws.africa/), who provide it with technical support.

**Comment by Sandravaphilips** [comment]
@NotoriousMBB hi! Can I have the logo, link and copy?

**Comment by niiroobiro** [comment]
@Sandravaphilips  
![Image](https://github.com/user-attachments/assets/7c6ac25e-0acc-44b3-ab0a-0d6926e6ddb6)

Link: https://oagmis.oag.go.tz/

**Comment by niiroobiro** [comment]
OAG abbrv needs to be replaced with the full name for clarity. **Office of The Attorney Genera**l

![Image](https://github.com/user-attachments/assets/4e3008fb-0c8d-4947-abb7-0d4b5e4ec856)
The link should be https://www.oag.go.tz/
