### ISSUE TITLE
Make login easier and remove bugs

### ISSUE THREAD

**Issue by ro6ley** [laws-africa/peachjam#213]
* [ ] Add button to the login page on the home page since Google login is not available via the admin
* [ ] Logging in via `https://agp.africanlii.org/accounts/login/` redirects to a missing profile page, redirect to the home page instead, or the Admin section by using the `LOGIN_REDIRECT_URL` setting

**Comment by longhotsummer** [comment]
I'm a little reluctant to add a log-in button, since you'd be surprised how many people will try to log in even though they don't need to. Since only content editors need to log in, perhaps we just get them to bookmark /accounts/login/, or add it as a small link in the footer.

**Comment by ro6ley** [comment]
> I'm a little reluctant to add a log-in button, since you'd be surprised how many people will try to log in even though they don't need to. Since only content editors need to log in, perhaps we just get them to bookmark /accounts/login/, or add it as a small link in the footer.

Understandably so, then maybe we could add the Google login button to the admin login page instead

**Comment by longhotsummer** [comment]
Good idea.
