### ISSUE TITLE
As a user on ZanzibarLII, I would like to see the Court of Appeal of Tanzania - Zanzibar registry on ZanzibarLII

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#2173]
The collection needs to be displayed on both the Judgments listings page: https://zanzibarlii.org/judgments/
and in search results.

**Comment by longhotsummer** [comment]
Currently judgments for this registry are on TanzLII, which we can consider authoritative. We need a mechanism to pull them into zanzibarlii, too.

**Comment by longhotsummer** [comment]
# Proposal

A peachjam-to-peachjam judgment ingestion adapter. We already have the ratification adapter.

* the ingestor must be able to accept a court code to filter on
* the judgment API must be able to filter by court code
* the court is configured in ZanzibarLII
* the ingestor is configured on ZanzibarLII to fetch judgments into the court

The TanzLII website would remain authoritative for the court's judgments, and they would be mirrored to ZanzibarLII.
