### ISSUE TITLE
Check staff permissions

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#2192]
We need to review the permissions that allow users to edit documents, especially the KL team making edits on Tausi.

**Comment by longhotsummer** [comment]
@actlikewill please describe the solution and the @Sandravaphilips can implement

**Comment by actlikewill** [comment]
Logged in users have the access to the 'Edit' button in the document detail view. That opens up the external document editing platform(indigo or caselaw) or local admin on the dropdown depending on the configuration. These both require that the user have the `coredocument editor` permissions. 
That permission is a little too high level to grant all editors. Instead we want to have those links only require that the user is a staff to view that button. 

![Image](https://github.com/user-attachments/assets/575a0bd2-d95c-4120-a7e0-e45b4717de1b)

Change the requirement for both of those to `user.is_staff`
