### ISSUE TITLE
Lawlibrary legislation listing page

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#273]
This page is a bit different to a normal document listing page, because we're trying to show a fair amount of document information and handle the fact that different users identify and look for legislation differently.

Aspects to consider:

* Acts are referred to both by their full name ("Child Justice Act, 2008") and by their numbered title ("Act 75 of 2008")
* Users may not know what act their looking for, and some indicator of subject area (or taxonomy filter) would be useful
* There are around 500 primary acts in most African countries. It's possible to show them all on the same page, and do client-side title filtering.
* Sorting by year and title (alpha) are both useful
* Acts have  subsidiary legislation (average of about 5, with a variance from 0 to 20+); advanced users will know that a certain regulation falls under certain acts; other users won't know this (eg. COVID-19 regulations fall under multiple Acts)
* We're listing works, not documents (because there are multiple amended versions of an Act)

# Outstanding

* [ ] how do we handle multiple languages in document listings?

**Comment by musangowope** [comment]
Patternfly approach to the legislation list:
- Pattern fly 3 has a dependency with bootstrap 3 and jquery min which conflicts with bootstrap 5
- Pattern fly 4 has UI components without automated js interactions

**Comment by longhotsummer** [comment]
@musangowope I don't recommend at all that we use the patternfly library. My suggestion was to use their examples to help us determine what we want to build.

**Comment by musangowope** [comment]
Yep, thats the approach I took

> @musangowope I don't recommend at all that we use the patternfly library. My suggestion was to use their examples to help us determine what we want to build.

Yep, thats the approach I took
