### ISSUE TITLE
As a developer I would like to have a utility to import various document types for a local instance

### ISSUE THREAD

**Issue by musangowope** [laws-africa/peachjam#289]
It would be nice to have an easy means to import all document types into a local developer instance.
Currently we have the ingestor to get generic documents from indigo which is great.
- Are we able to get other documents types from the ingestor as well?
- Perhaps seeders might be another avenue to explore?
- Having supporting documentation for this would amazing

**Comment by musangowope** [comment]
@actlikewill would the ingestor be good means for this? If so, could you chat me this, and we could write documentation to add to the `Readme.md`

**Comment by actlikewill** [comment]
> @actlikewill would the ingestor be good means for this? If so, could you chat me this, and we could write documentation to add to the `Readme.md`

@musangowope We can add some fixtures to the codebase. Let me pick this up.
