### ISSUE TITLE
Deploy to new.lawlibrary.org.za

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#290]
* [x] domain
* [x] dokku app setup
* [x] postgres db
* [x] configure app settings, such as elasticsearch and S3 details
* [x] how to configure django to run lawlibrary not peachjam  -  set env `DJANGO_SETTINGS_MODULE=lawlibrary.settings`
* [x] setup auto deploys

**Comment by ro6ley** [comment]
This was deployed to `lawlibrary.staging.laws.africa`. Should it have been `new.lawlibrary.org.za`?

**Comment by longhotsummer** [comment]
I don't think it's a critical issue at this point.
