### ISSUE TITLE
Document ingestors need a way to identify documents deleted at their source that also need to be deleted locally

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#304]
## Proposal

- We need to add a mechanism to compare what we have in the local database to what we have at the remote ingestor source and keep them in sync. 
#### Indigo Adapter
- At the point where gather the `points in time` urls for updating, we can add a check for existing related works using the Work model and compare them with the list of urls in the point in time object. 
- If we have existing documents for the Work that are not in the point in time object, we can delete them

#### Gazettes Adapter

- For gazettes, we can do a straight comparison for values which are in the current database that do not exist in the Gazettes.africa database for the current jurisdiction. We delete the ones that we have in the database that do not exist in Gazettes.africa database.

**Comment by longhotsummer** [comment]
This also applies to gazette ingestion and the gazette adapter.

**Comment by longhotsummer** [comment]
See also #528 -- the mechanism to link an ingested document to its ingestor is common to both.

**Comment by actlikewill** [comment]
@longhotsummer I have added the proposal to this issue let me know if it works.

**Comment by longhotsummer** [comment]
@actlikewill at a high level this makes sense.

The ingestor system asks the adapter for a list of documents, and then queues up background tasks to update those documents. How will deletion fit into that?

Perhaps the adapter returns a list including documents that should not exist locally, and when `update_document` checks for the document on the server (and can't find it), it deletes it instead of updating it?

Alternatively:

1. deletion happens during `check_for_updates` which seems a dangerous side effect; or
2. the ingestor system will need to differentiate between documents to update, and documents to delete.

**Comment by actlikewill** [comment]
@longhotsummer I've seen that we have some scaffolding for deletion in the ingestor. I think that the logic for distinguishing documents for update and delete needs to be on the check_for_updates method. Here we can compile a list of documents for deletion and setup bg tasks to do the actual deletion

**Comment by longhotsummer** [comment]
I think `check_for_updates` is the right place to determine what needs to be deleted, and then it delegates to something else to actually do the deletion. Go for it.
