### ISSUE TITLE
Add citations in document title for au resolutions

### ISSUE THREAD

**Issue by actlikewill** [laws-africa/peachjam#318]
- It would be useful to the content team to have the citations for the resolutions inside the title.
- We can have a method that constructs the title before saving and indexing it on elastic search.

**Comment by longhotsummer** [comment]
@actlikewill do you mean pulling in the citation into the title, like we do for Judgments? eg. `Resolution on Cool Things (RES 1/22/3)`

**Comment by longhotsummer** [comment]
For content coming from external sources, the title must be set there. We now index, search and show citations separately, which I think is sufficient for now.
