### ISSUE TITLE
Detail page should prompt to load large pdf

### ISSUE THREAD

**Issue by musangowope** [laws-africa/peachjam#356]
> > @longhotsummer On the task to prompt to load large files, what is the threshold for a large file? Also what is the best way to handle this, should we alter the response on the document source pdf view or should we handle it with the frontend javascript?
> 
> I believe this functionality already exists in Peach Jam for large files? @musangowope can you confirm?

@longhotsummer.  We did discuss the idea for this feature in the past but it does not yet exist. I'm going to go ahead and make a ticket on peachjam for this feature.

_Originally posted by @musangowope in https://github.com/laws-africa/gazettemachine/issues/104#issuecomment-1232577550_

**Comment by musangowope** [comment]
Process:
- If pdf document is large, give user decision to either "Proceed to load document" or "Cancel"
- If the user selects cancel, loading does not proceed. They can download the document from meta block link. 
(Perhaps provide the option to load the document again?)

Questions:
- What size does the pdf need to be for this to happen?

**Comment by longhotsummer** [comment]
Thanks Musango

I don't think there needs to be a cancel. Just the button to load the PDF if they want to.

Since it's a pdf thing, it should be done as part of the pdf viewer. 

I suggest a threshold configurable via the django view class. Set it as a data attribute. 

5MB by default?
