### ISSUE TITLE
Consistently apply the term Regional Body across the AGP website

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#427]
as a label for Author, e.g. the metadata section of a treaty display page
![image](https://user-images.githubusercontent.com/46931873/190914404-194a831b-51ce-41a2-a325-5a1424b2af4d.png)

e.g. filter on search results page
![image](https://user-images.githubusercontent.com/46931873/190914464-a780910f-92cf-4d46-825f-776edd4405e4.png)

**Comment by longhotsummer** [comment]
## Proposal

Using different terms for different database models seems like it will come up in a few places. Without trying to solve a problem that we don't know we have yet, I suggest the following to try out a potential path that will solve the current challenge and tell us if it's a reasonable way forward.

* On the `Author` class, add a variable (not a db field, just a normal class-level variable) called something like `model_label` that defaults to `_('Author')` (not `_` for translations)
* In AfricanLII's `ready()` we do something like `Author.model_label = _('Regional body')`
* That variable is available on the class and on objects where necessary
* Use that variable in templates
* For javascript facets, pass in a JSON `labels` dictionary that provides a translated label for the `Author` model. eg. `data-labels="{'Author': 'Regional body'}".

That way the translated and adjusted string is available to templates and javascript from a single source, and still gets translated.
