### ISSUE TITLE
As a user of search, I would like to easily see the Author information on individual search results

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#429]
without having to open the link to check the document
![image](https://user-images.githubusercontent.com/46931873/190914836-c5d6eba8-5609-40f1-86f2-4b46ce4085e2.png)

**Comment by longhotsummer** [comment]
Blocked by #432

**Comment by nickmwangemi** [comment]
@longhotsummer Could you please provide more context?

**Comment by longhotsummer** [comment]
I suggest doing this:

To the right of the date, add `item.court` if it is available, in the same way we add `item.author`.

![image](https://user-images.githubusercontent.com/4178542/194037371-8da6512d-9d5a-4913-95e1-396689949ed3.png)

Look in SearchResult.vue

**Comment by longhotsummer** [comment]
Merge https://github.com/laws-africa/peachjam/pull/515 first, however, to fix the serialising of the author.

**Comment by longhotsummer** [comment]
Can you also do https://github.com/laws-africa/peachjam/issues/493 at the same time -- put the document type `item.doc_type` immediately to the right of the date. Both `item.date` and `item.doc_type` will never be null.

**Comment by longhotsummer** [comment]
Just to call out that `author` is actually there, but #515 fixes a serialiser bug. So this issue is now about also showing the `court` information, in addition to the author :)
