### ISSUE TITLE
As a content editor, I'd like to be able to see the full case name as I am typing it in

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#440]
the judgment capture form field. Some case names are very lengthy and reviewing the final case name before saving is difficult.

![image](https://user-images.githubusercontent.com/46931873/191079214-ceb64977-c7ad-46e2-9684-dde7395293b2.png)

**Comment by NotoriousMBB** [comment]
as submitted by a content editor today

**Comment by longhotsummer** [comment]
This is now much wider, although long case names will still clip on the right.
