### ISSUE TITLE
AfricanLII and LawLibrary: Show terms of use and content licensing

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#443]
# AfricanLII

* [x] develop TOS and content licensing
* [ ] link from footer

# LawLibrary

* [x] develop TOS and content licensing
* [ ] link from footer

**Comment by NotoriousMBB** [comment]
AfricanLII TOC: https://docs.google.com/document/d/13KGPUsvB6W8TG6SzwiA-dwSnF3kFMjOPCWVCJTP_xXI/edit?usp=sharing

**Comment by NotoriousMBB** [comment]
LawLibrary: https://docs.google.com/document/d/1xbGV3jo_yh3lWhvPvzZFoj57pjxsI5m4jWo98mXYgoM/edit#
