### ISSUE TITLE
Ulii: show gazettes from gazettes.africa

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#449]
The goal is to have SA gazettes on LawLibrary itself, in search, etc.

However, we ideally don't want to duplicate all the gazette files from S3 and rather rely on the S3 storage from Gazettes.Africa. 

* [x] an updated gazette document model that is able to delegate to the file stored in the Gazettes.Africa S3 bucket
* [x] correct integration into search
* [x] don't delete the gazettes from S3 when deleting the object
* [x] gazette model in peachjam
* [x] listing pages for gazettes
* [x] detail pages for gazettes
* [x] an ingestor to "fetch" SA gazettes from Gazettes.Africa as they are uploaded
* [x] integrate into ulii site navigation
* [x] don't duplicate downloads unnecessarily https://github.com/laws-africa/peachjam/issues/790

## Proposal

* Create a new Gazette model; no new fields are required
* Top-level gazette listing page as on https://gazettes.africa/gazettes/za/, for the url: `/gazettes`
* Single-year listing page as on https://gazettes.africa/gazettes/za/2022, for the url: `/gazettes/<year>`

**Comment by longhotsummer** [comment]
This would be relatively straight-forward if we the bucket was stored in the "filename" part of the `file` object that is written to the db. Currently it only stores the S3 object key, not the S3 bucket (that is assumed to be global).

**Comment by longhotsummer** [comment]
An alternative is to delegate to an actual URL, rather than just an S3 bucket. So maybe we mark the source file as at a remote URL?

**Comment by longhotsummer** [comment]
It's possible to make our own FileField which can determine dynamically the bucket to use based on the object filename: https://medium.com/@hiteshgarg14/how-to-dynamically-select-storage-in-django-filefield-bc2e8f5883fd

**Comment by longhotsummer** [comment]
I'll use https://github.com/mcclory/django-dynamic-storages instead which has good scaffolding for this.

**Comment by longhotsummer** [comment]
Partially implemented by #610 which adds support for  different S3 buckets.

**Comment by longhotsummer** [comment]
## Proposal

* Create a new Gazette model; no new fields are required
* Top-level gazette listing page as on https://gazettes.africa/gazettes/za/
* Single-year listing page as on https://gazettes.africa/gazettes/za/2022

**Comment by longhotsummer** [comment]
https://github.com/laws-africa/peachjam/pull/716 adds the gazettes ingestor

**Comment by nickmwangemi** [comment]
https://github.com/laws-africa/peachjam/pull/816  integrates gazettes into ulii
