### ISSUE TITLE
As a content editor, I'd like to upload the original PDF supplied by the Court.

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#455]
Currently, I get an error 
![image](https://user-images.githubusercontent.com/46931873/191904215-0e1d5ba9-b38b-408a-b246-df643bf2b586.png)

**Comment by longhotsummer** [comment]
That image file doesn't load.

Is this in addition to the source file? eg. a judgment is created from a .docx and then you'd like to add a supplementary PDF file?

**Comment by NotoriousMBB** [comment]
Yes, this is a PDF in addition to the source file. Some courts send us both a Word and a PDF version. 
We also sometimes convert scanned PDFs and use the Word version to create a page, but still need the scanned PDFs as the original document to compare in case of OCR errors etc.

**Comment by longhotsummer** [comment]
Got it, thanks. This is entirely unsupported right now.

**Comment by longhotsummer** [comment]
I think we should support this by changing the current "MediaSummaryFile" feature, into a more generic 1-to-many "AttachedDocuments" model which has a configurable "nature", such as "media summary" or "original PDF". Because there are bound  to be similar requirements for supporting documentation later.

**Comment by longhotsummer** [comment]
# Proposal

* new `AttachedFiles` model that extends the abstract attachment model; the new model has a foreign key back to CoreDocument
* the new model has a `nature` FK field
* a new `AttachedFileNature` field, with a name and a description 
* replace JudgmentMediaSummaryFile with the above
* show these attached files as additional downloads in the metadata block of the document

The idea is that the user can upload an arbitrary number of related documents (could be spreadsheets, PDFs, whatever) that we don't process at all, and simply show as downloadable files.

An argument against a generic model like this is if we want to give special treatment to certain types of attached files, which is always a bit awkward when things are generic. However, we can still do that by filtering against specific values of `nature`.
