### ISSUE TITLE
Image wonky - positioned in the top left corner of the page

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#456]
Windows|Chrome

https://lawlibrary.org.za/akn/za/judgment/zagpjhc/2022/48/eng@2022-02-11

![image](https://user-images.githubusercontent.com/46931873/191836937-85fb71e1-02d4-4c58-aa29-a01916679730.png)

**Comment by longhotsummer** [comment]
Solution:

* [ ] During HTML import, add a pipeline stage to strip "position: absolute" from HTML style tags

**Comment by longhotsummer** [comment]
We can then do a db query to see how many documents have "position: absolute" in the HTML and either re-process manually, or in a batch.

**Comment by longhotsummer** [comment]
Impacted documents have been fixed.
