### ISSUE TITLE
Integrate with Indigo so that ingestion happens almost immediately

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#458]
Once an indigo document is signed off, it should appear almost immediately in a peach-jam system. Our pull mechanism makes this difficult.

## Proposal

Setup a two-way system. The Publication Outlet on Indigo is useful because it shows in Indigo where the document is published too, and offers us push-based synchronisation.

* create a new peachjam Publication Outlet adapter in Indigo
* when a work is signed off in Indigo, the publication outlet will trigger the adapter
* the adapter then calls out to a webhook API on peachjam, telling the peachjam ingestor to pull the update
* the peachjam ingestor does its normal work

Effectively, the webhook immediately queues up a peachjam update task to update the document. This may also help when a document has been *unpublished*.

Still to be determined:

* how do we link the webhook call to the correct peachjam ingestor? Can we provide a parameter to the Indigo adapter that it sends together with the webhook, such as the id of the peachjam ingestor?

## What about the current periodic ingestor?

We will keep the daily ingestor updates that are already configured.

**Comment by longhotsummer** [comment]
@actlikewill what's still outstanding here?

**Comment by actlikewill** [comment]
@longhotsummer The code is merged to both indigo and peachjam. We need to configure the ingestor and test if it works.

**Comment by longhotsummer** [comment]
I've tested this and it looks like everything works smoothly. We have the new publication outlets in indigo and the notification is correctly published to lawlibrary, which responds by running the background update tasks.
