### ISSUE TITLE
Add contact form on lawlibrary

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#464]
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLScrIGxy1Qs-lb4FA1myX1uv1u_pCAVUJ6as_w4QbQLmCJZK7Q/viewform?embedded=true" width="640" height="677" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>

**Comment by musangowope** [comment]
Perhaps we can follow the same pattern as AGP africanlii? About us page with the contact form? Let me know what you think about this
https://agp.africanlii.org/about/
