### ISSUE TITLE
As a user, I'd like to have a better reading experience with PDF judgments

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#468]
PDF judgments do not display well on mobile.
![pdfjudgmentonphone](https://user-images.githubusercontent.com/46931873/192331977-31b8fa07-1329-4896-b615-4b196edcee69.jpeg)

**Comment by musangowope** [comment]
We'll need into what platforms have done to provide the best possible experience for viewing pdfs on mobile

**Comment by longhotsummer** [comment]
I see two aspects to this:

## Desktop

* #399 

## Mobile

* render the PDF page to take up the full width of the viewport.
* Allow the user to pinch-to-zoom (already supported)

This would mimic the same experience that the user has reading PDFs on mobile in a native PDF reader / browser.

I think the desktop and the mobile solutions are actually the same: determine the width of the box in which to render PDF content, and render each page to the full width of that box. Then it's a matter to constricting the size of the box on wider displays.
