### ISSUE TITLE
As an editor on peachjam, I should be able to add content for past years, while being unable to add content with dates beyond the present day

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#542]
On peachjam add years back to 1910 on hearing and judgment dates, and remove option to add forward dates. Currently editors are able to add dates only from 2022 forward.  The last date available to editors to add should be today.

![image](https://user-images.githubusercontent.com/46931873/195418958-c3d621d0-49d8-461f-9fe2-5603fdaa30fd.png)

**Comment by longhotsummer** [comment]
Will be fixed by #549

**Comment by longhotsummer** [comment]
done
