### ISSUE TITLE
Add basic functionality to annotate all documents on the platform and display the annotation in the gutter

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#547]
Basic orienting text could be **Read more**, followed by the link. The editor should be able to specify the text of the link and not display plain URL

See https://agp.africanlii.org/akn/aa-au/act/charter/1990/rights-and-welfare-of-the-child/eng@1990-07-01#part_I-Rightsandduties__chp_One__art_XXII  and commentary to it  https://agp.africanlii.org/akn/aa-au/doc/acerwc/2020-09/general-comment-on-article-22-of-the-african-charter-on-the-rights-and-welfare-of-the-child-children-in-situations-of-conflict/eng@2020-09-01 
![Comment](https://user-images.githubusercontent.com/46931873/196112876-f7a85442-ff50-4e97-845d-639365a5e341.png)

**Comment by longhotsummer** [comment]
Greg to take Mariya through our existing functionality to see if it suffices.

**Comment by longhotsummer** [comment]
I'm closing this for now as we have the relationships annotations feature.
