### ISSUE TITLE
The list displayed on the alphabetical listing post-filtering should sort the results alphabetically

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#555]
Reference page: https://agp.africanlii.org/legal_instruments/?alphabet=a

Explanatory video:
https://www.loom.com/share/13d324262b81410f81c04fabb7f3b804

**Comment by longhotsummer** [comment]
If an alphabetical filter is applied, the change the ordering to `title`.

**Comment by nickmwangemi** [comment]
https://www.loom.com/share/615b51e52ba94217aa94ad872cc09cc6

**Comment by longhotsummer** [comment]
> The requested functionality is already available:
> 
> https://www.loom.com/share/615b51e52ba94217aa94ad872cc09cc6
> 
> It was handled by #719

That's only because those views now order by title by default.

https://agp.africanlii.org/judgments/?alphabet=a orders by date by default, and should change to title when an alpha filter is applied.

**Comment by longhotsummer** [comment]
If possible, try do this in the base filtered document view class, so it applies everywhere.
