### ISSUE TITLE
As an advanced user I want advanced search that gives me field-based search and similar things

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#564]
eg. https://juricaf.org/recherche_avancee

Also consider "does not contain", "contains exactly" etc.

**Comment by longhotsummer** [comment]
I see two major aspects here:

* Field-based search/filter allows the user to specify search terms or filters for different fields, such as the citation or title of the document.
* Boolean query strings which allows for "foo AND (bar OR baz) AND NOT boom" style queries.

Let's consider these things separately. This issue is for field-based search, and https://github.com/laws-africa/peachjam/issues/583 is for boolean queries.

**Comment by musangowope** [comment]
### Implementation:
- Create tabbed content with tabs: `Search` and `Advanced`
- `Search tab` will contain the original existing Search input
- `Advanced tab` will contain an Advanced search form
- Use [bootstrap tabs](https://getbootstrap.com/docs/5.0/components/navs-tabs/) to achieve this functionality

**Advanced search form:** 
Some guidelines:
- Create a new component called AdvancedSearch which holds the form for the advanced search
- Wrap the form inside [bootstrap card](https://getbootstrap.com/docs/4.0/components/card/)
- Use `form control` css class for inputs

This form will contain the following fields:
| Label | Fied type |  key |
| --- | --- | --- |
| Title | textfield | title |
| Date | date | date |
| Citation | textfield | citation |
| Content | textfield | content |
| Created at | date | created_at |
| Updated at | date | updated_at |
| Headnote holding | textfield | headnote_holding |
| Flynote | textfield | flynote |
| Judges | textfield | judges |
 
The UI would look something like this (Ignore the fields present)
<img width="905" alt="image" src="https://user-images.githubusercontent.com/15995210/198004414-f629e15c-395f-4d50-a40d-b2dfb49d0a7d.png">

On submit of the advanced search form, use the key/value of the inputs in the form to request results. 
E.g if title field value is `Law` and the judges field value is `Foo`
the get request would look like this `/search/api/documents/?search=judges:Foo&search=title:Law` 

My suggestion would be to set up the layout first.  After that, we can chat through the data-requesting functionality. There will probably be a few edge cases we need to handle.

@longhotsummer, lmk what you think about this

**Comment by longhotsummer** [comment]
Nice. Some thoughts:

* I don't think you need the "Advanced Search" card title if the tab says "Advanced Search" since it acts as a title
* Right-align the "Search" button (the card footer element does this for you)

How should date fields be handled? Since I suspect date range searches will be most common, we should help the user specify "after X", "before Y" and "after X and before Y". Perhaps two date fields: before and after. If either is blank, it is ignored. `<input type="date">` may be sufficient for each input box? I don't know if you can "clear" those.

**Comment by longhotsummer** [comment]
We don't need `created_at` or `updated_at` for now -- they don't have much external meaning.

**Comment by longhotsummer** [comment]
## Backend changes required

Out the box, elasticsearch-dsl-drf doesn't support multiple-field search, so we'll need to add this. Our page-based search also doesn't interact well with this.

* [ ] in SimpleQueryStringQueryBackend we need to allow handling multiple `search=` params
* [ ] the multiple queries must be joined in a single `must` (rather than should)

Here's what it generates currently once we support multiple search params. The should/must and the content search isn't great:

```js
"should": [
        {
          "simple_query_string": {
            "fields": [
              "title^6"
            ],
            "query": "refugee"
          }
        },
        {
          "simple_query_string": {
            "fields": [
              "content"
            ],
            "query": "fun"
          }
        },
        {
          "nested": {
            "inner_hits": {
              "_source": [
                "pages.page_num"
              ],
              "highlight": {
                "fields": {
                  "pages.body": {}
                },
                "fragment_size": 80,
                "number_of_fragments": 2,
                "post_tags": [
                  "</mark>"
                ],
                "pre_tags": [
                  "<mark>"
                ]
              }
            },
            "path": "pages",
            "query": {
              "bool": {
                "must": [
                  {
                    "simple_query_string": {
                      "default_operator": "and",
                      "fields": [
                        "pages.body"
                      ],
                      "query": "title:refugee content:fun",
                      "quote_field_suffix": ".exact"
                    }
                  }
                ],
                "should": [
                  {
                    "match_phrase": {
                      "pages.body": {
                        "query": "title:refugee content:fun",
                        "slop": 2
                      }
                    }
                  }
                ]
              }
```

**Comment by longhotsummer** [comment]
https://github.com/laws-africa/peachjam/pull/628 adds per-field advanced search.

**Comment by longhotsummer** [comment]
Closing this in favour of #583 for the outstanding functionality.
