### ISSUE TITLE
As a non-expert user I'd like background information on a court or regional entity

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#584]
Can we add info to the court and author/regional body detail pages to help a non-expert user get an understanding of where they fit in the bigger picture? Like a mini bio on pages such as https://lawlibrary.org.za/judgments/ZACC/  and https://agp.africanlii.org/authors/7/

Perhaps these elements:

* a brief overview, 1-2 paras (from wikipedia?)
* an image (eg. a photo of the court)
* a website address
* a physical address

## Modelling changes required

* a new EntityProfile model which has a generic foreign key to any other model type (eg. taxonomy, document, court, etc.)
* about_html: an HTML field for about text (optional)
* website_url: URL field for the website (optional)
* address: a text field for an address (optional)
* photo: an image field for a profile photo (optional)

**Comment by longhotsummer** [comment]
I think we need a mockup to see what this would look like.

**Comment by musangowope** [comment]
@longhotsummer 
Here is the proposed mockup for the court or regional entity page
![Court page](https://user-images.githubusercontent.com/15995210/198052536-fe5388a7-7e25-46e0-828c-77adb7de9993.jpg)
Please let me know what you think.

**Comment by longhotsummer** [comment]
Brief notes from our discussion:

* "visit site" should be a link with the website address, to help users see what it actually is
* we'd probably put all page headers into the grey background, not just those with info
* how does this work on mobile?
* what would it look like to fit an optional banner image in?

**Comment by musangowope** [comment]
![Regional entity page desktop](https://user-images.githubusercontent.com/15995210/199744309-0928e98f-9206-4ead-b186-d82567377221.jpg)

![Regional entity page mobile](https://user-images.githubusercontent.com/15995210/199744316-f677b4a3-372a-4a7f-b358-bf4f58aeb02c.jpg)

![Regional entity page with background desktop](https://user-images.githubusercontent.com/15995210/199744323-6e653fef-5112-420c-ba18-822fe33cbd83.jpg)
