### ISSUE TITLE
Some document types make more sense to order alphabetically, rather than date

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#597]
For example, https://agp.africanlii.org/legal_instruments/ are more useful ordered alphabetically by title

Order `GenericDocument` by `title`.

**Comment by longhotsummer** [comment]
For these document types, it may also help users to put the alpha facet above the year facet.

**Comment by nickmwangemi** [comment]
@longhotsummer Order both generic documents and legal instruments?
