### ISSUE TITLE
As a user of the French version of the AGP site, I would like the search to recognise language-specific characters

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#611]
[@Mariya](https://africanliiteam.slack.com/team/UB3CBRWDR)
 French accents and searching: just noting that on https://agp.africanlii.org/ when one does a search for differends one does not pickup the items with différends. This must have implications for users who don't use accents on letters when searching, I am sure this can be tweaked to pick up both?

**Comment by longhotsummer** [comment]
I think we can use a similar approach to #177. We'll have to look into how we index different languages separately and then search multiple indexes concurrently.

**Comment by longhotsummer** [comment]
Refs:

* https://www.elastic.co/blog/multilingual-search-using-language-identification-in-elasticsearch
* https://codarium.substack.com/p/designing-an-optimal-multi-language
