### ISSUE TITLE
As a user of a peachjam website, I would like to discover with ease documents that are usually referred to by their popular names or abbreviations 

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#616]
Legal instruments and other documents in the AU ecosystem are frequently referred to by their abbreviations or short names. For example:

* the African Charter on Human and Peoples' Rights is known as the Banjul Charter
* the African Charter on Democracy and Elections is referred to as the ACDEG
* the Protocol to the African Charter on Human and Peoples' Rights on the Rights of Women in Africa is better know as the Maputo Protocol.

References in resolutions, decisions and policy documents would often use these popular references instead of the full title of the document.

Between what we can do on the Indigo Platform and the search engine of the AGP website, what would be the best way to facilitate the users' discovery of these materials?

**Comment by longhotsummer** [comment]
## Proposal

We create a new one-to-many model for CoreDocument called AlternativeName; this is a list of strings that are alternative names for the document. They are included when indexing the document into Elasticsearch, and are also shown on the document detail page.

Aliases are linked to a document (not a work) and are therefore in a particular language. For example, an English document would have "Banjul Charter" whereas the French document would have the French equivalent.

These will be set on a document manually.
