### ISSUE TITLE
As a mobile user of the AGP website, I would like to be able to read the gutter annotations on peachjam documents

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#617]
Android mobile phone users currently do not see annotations associated with highlights, as pictured below 

![Screenshot_20221029-191337_Chrome](https://user-images.githubusercontent.com/46931873/198874178-27ba0c0a-9d65-40ac-a1a9-95050d0fad8c.jpg)

**Comment by musangowope** [comment]
@longhotsummer I have made a very quick mockup of what this could look like

On click of the highlighted text, the relevant annotation pops up like this:
![Mobile Annotations](https://user-images.githubusercontent.com/15995210/201082291-34846a2f-9f4a-4f85-9a4e-468f8ffa5b19.jpg)

The second aspect is to make it known to the user that they can view annotations on a mobile phone. So on the first time of looking at an akn document on mobile, a modal popup could appear, giving a brief demo (in the form of a gif) showing the clicking of highlighted text.
The user will also have the option not to show this help modal again (We can store the option in the cache)

So it would look something like this:
![Alert user](https://user-images.githubusercontent.com/15995210/201083330-6a6584d6-edd6-4127-8b7e-bd15d0886061.jpg)

Let know me what you think about this

**Comment by longhotsummer** [comment]
Nice.

When the popup is shown, is it fixed to the bottom of the display? What does the orange arrow do?

I think the help modal is too heavy handed. If we put an icon to the far right and the text is coloured, I think that's tempting enough for users to tap on and discover. Remember: users don't read instructions.

**Comment by musangowope** [comment]
> When the popup is shown, is it fixed to the bottom of the display? What does the orange arrow do?
Yes, the popup is fixed to the bottom. We can remove the orange arrow. I initially just took it from the current annotation card shown in the gutter but I realize now that that orange arrow is for admin actions which is not needed in mobile viewing.



> I think the help modal is too heavy-handed. If we put an icon to the far right and the text is colored, I think that's tempting enough for users to tap on and discover. Remember: users don't read instructions.

Agreed, an icon on the far right would suffice. Perhaps a speech icon?  Rough mock-up of what that could look like
![Speech icon](https://user-images.githubusercontent.com/15995210/201597151-1d31b041-8ba5-47a0-bffa-a445d57c970d.png)
We'll need to experiment with spacing

**Comment by longhotsummer** [comment]
> > When the popup is shown, is it fixed to the bottom of the display? What does the orange arrow do?
> > Yes, the popup is fixed to the bottom. We can remove the orange arrow. I initially just took it from the current annotation card shown in the gutter but I realize now that that orange arrow is for admin actions which is not needed in mobile viewing.
> 
> > I think the help modal is too heavy-handed. If we put an icon to the far right and the text is colored, I think that's tempting enough for users to tap on and discover. Remember: users don't read instructions.
> 
> Agreed, an icon on the far right would suffice. Perhaps a speech icon? Rough mock-up of what that could look like ![Speech icon](https://user-images.githubusercontent.com/15995210/201597151-1d31b041-8ba5-47a0-bffa-a445d57c970d.png) We'll need to experiment with spacing

The comment icon looks good. As you say, spacing will be a consideration.

I think this is good enough to implement so we can play with it and see how it feels.
