### ISSUE TITLE
Chore: Migrate AGP to AfricanLII servers

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#618]
We'll need to coordinate with AfricanLII. The most urgent aspect of this is moving to the new dokku server -- our server is overloaded.

# High priority

* [x] server to use
* [x] add the SSH key we use for github deployments
* [x] update deployments workflow
* [x] move DNS

# Lower priority
* [ ] copy S3 data into a new bucket

**Comment by ro6ley** [comment]
AGP is now running on Liiweb servers, deployment key added and DNS entry for agp.afrincanlii.org updated

**Comment by longhotsummer** [comment]
I'm closing this as done. When we implement #551 we can also migrate the S3 data.
