### ISSUE TITLE
As a user of the AGP site, I would like to be able to filter lists of documents under a specific body, by the type of document

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#638]
rather than the system name **generic document** which does not map to my understanding of the document classes I know this body to produce. 
See https://agp.africanlii.org/authors/15/
![image](https://user-images.githubusercontent.com/46931873/199551713-e527e456-d82e-456b-b533-bcc2e67f1f75.png)

**Comment by NotoriousMBB** [comment]
In this case Generic document is not useful, rather that these are Decisions is meaningful
![image](https://user-images.githubusercontent.com/46931873/199551849-21f4ef52-fe1f-4996-9419-a2d64e59ab85.png)

**Comment by longhotsummer** [comment]
The document type filter should be using document nature, instead, which takes generic documents into account.

Ref also #714

**Comment by longhotsummer** [comment]
This is a tad more complex in the Author view, because the subclass doesn't know that the author view can use both judgments and generic document, so it doesn't facet the document type or nature correctly.

**Comment by longhotsummer** [comment]
Yes, it looks like this is done.
