### ISSUE TITLE
Chore: ensure compatibility with pocketlaw

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#668]
* [x] what external domains must be included in a crawl (eg. google fonts)
* [x] how do we determine what files to download / not download? (eg. gazette PDFs)
* [x] ensure we only scrape in the default language (languages are set with a POST, so this should be fine)

## outstanding
* [x] how does `wget` get all links to follow for legislation, given that the legislation list is rendered by Javascript?
* [x] integrate with search

## Listing pages

Some functionality on the document listing pages make the number of static pages we must scrape explode. All the facet options (eg. alphabetical, years, judge) will do this.

Instead, we can disable facets in pocketlaw. I suggest we do this by injecting a CSS class onto the body of the document in pocketlaw, eg `class="is-pocketlaw"` and use CSS inside peachjam to hide those features we know do not work on pocketlaw. We could even go further and include `class="is-pocketlaw is-pocketlaw-offline"` and only disable them when the page is being served offline.

**Comment by longhotsummer** [comment]
## Legislation links

wget naively loads the page and follows links. Because JS is used to render the legislation tables after loading, the page doesn't actually contain links and so wget won't download them.

Options

1. a comprehensive sitemap page with all content (which is also useful for other search engines) -- we need to explicitly tell wget to download the xml and then fetch all the links, so it's not a very organic solution
2. include a simple html table of links in the legislation page which is then replaced by javascript with the richer table. This has the benefit of being a nice fallback if JS doesn't load (not a very common case) and integrates easily with search engines and with wget, at the cost of a larger page.

**Comment by ro6ley** [comment]
Test lawlibrary crawl -> https://www.loom.com/share/1617dabfd6a14f64abc14b9e7139ad8e 

Notes:
- Gazettes are hosted externally, so weren't part of this crawl
- Crawl was executed recursively up to only 2 levels, hence some broken content links
- Some facets work, some don't

**Comment by ro6ley** [comment]
Related PRs:
- Warc processor update to handle peachjam warcs [pocketlaw-automation #4](https://github.com/laws-africa/pocketlaw-automation/pull/4)
- Pocketlaw update to handle peachjam warcs [pocketlaw #452](https://github.com/laws-africa/pocketlaw/pull/452)

**Comment by ro6ley** [comment]
> Instead, we can disable facets in pocketlaw. I suggest we do this by injecting a CSS class onto the body of the document in pocketlaw, eg class="is-pocketlaw" and use CSS inside peachjam to hide those features we know do not work on pocketlaw. We could even go further and include class="is-pocketlaw is-pocketlaw-offline" and only disable them when the page is being served offline.

To disable facets in Pocketlaw:
- add css class to all elements to be hidden or removed in pocketlaw, e.g. `class="pocketlaw"` or `class="pocketlaw-ignore"`
- add JS script to main layout page that:
  - checks for the user agent
  - if the user agent includes pocketlaw, find all elements with the class above and remove them

Electron automatically adds the app name and version to the user agent, e.g. Pocketlaw v1.0.5 running Lawlibrary will have the following user agent string: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) PocketLaw-LawLibrary/1.0.5 Chrome/98.0.4758.82 Electron/17.0.1 Safari/537.36`

**Comment by ro6ley** [comment]
### Outstanding

- PDFs will not load due to how Django handles static files by adding hash values to the names, e.g. `https://lawlibrary.org.za/static/lib/pdfjs/pdf.worker.js` becomes `https://lawlibrary.org.za/static/lib/pdfjs/pdf.4a2a1c0fb5fb.js`  and the worker.js is not available in the archive. This applies to static files mostly
-
