### ISSUE TITLE
As a French user of a peachjam website, I'd like to read the date in the title of judgments in French

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#680]
currently, it displays in English in the FR view
![image](https://user-images.githubusercontent.com/46931873/201856451-aa77752a-50ea-40a0-a02d-24ff6877ac6d.png)

**Comment by longhotsummer** [comment]
If the document is in French then we should engage the French translations when formatting the date in the title.

We can't (right now) dynamically show French-formatted dates for English documents when the user is browsing in French.
