### ISSUE TITLE
SGBV taxonomy list is difficult to navigate and read because it is very long

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#683]
This is great but too many green links, that are difficult to distinguish

https://lawlibrary.org.za/taxonomy/collections/sexual-and-gender-based-violence

**Comment by NotoriousMBB** [comment]
Being able to search the taxonomy like searching the TOC would be very useful (different issue)

**Comment by longhotsummer** [comment]
I see a few options here, we probably want to do a mix of things:

* ensure only taxonomy entries that are used are included (less confusing to the user)
* move the top level entry into the box as the heading, to give the list a bit more room on the left
* restrict the height of the list and scroll when it overflows
* add searching (usual TOC component search)
* nest the taxonomy a little to make it less imposing
* make wrapped lines more readable by resetting line height to normal and adding some margin below each item (currently wrapped lines and separate items are indistinguishable)
