### ISSUE TITLE
Timeline for older legislation expressions don't have newer events

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#692]
https://lawlibrary.org.za/akn/za/act/1996/constitution/eng@2009-04-17

Update the code to use `work_amendments` rather than `amendments` from the metadata json. Because some old data still exists, fall back to `amendments` if `work_amendments` is not available.

**Comment by longhotsummer** [comment]
this is because we use `document.amendments` from the API, rather than pulling together all the amendment events for the full work.

**Comment by goose-life** [comment]
`work_amendments` is now available via the API

**Comment by nickmwangemi** [comment]
@longhotsummer @goose-life Will `work_amendments` always contain more events than `amendments`?

**Comment by longhotsummer** [comment]
No. On the latest point in time it will usually (but not always) be the same.
