### ISSUE TITLE
As a reader I want to know that amendments are being applied to a work

### ISSUE THREAD

**Issue by goose-life** [laws-africa/peachjam#697]
Once #692 is resolved, all amendments (whether they have associated content or not) should show up in the timeline / 'History' tab.

But there should be a notice as well, similar to the "this isn't the latest point in time" notice, that calls out that the work has been subsequently amended, preferably linking to the amending work (if it exists).

**Comment by longhotsummer** [comment]
These are new notices just for legislation, much like the "This is the latest version of this Act" notice.

@goose-life can provide the details of how and when they should be constructed.

**Comment by goose-life** [comment]
But there will also be instances of multiple unapplied amendments, especially stubs, and I don't think we should list all (or any) of them then. In that case let's point them to the History tab instead. In fact, let's just always do that.

`This {friendly_type} has been amended again since {latest expression date}. See [History](#) for more information.`

**Comment by goose-life** [comment]
If the current expression is the latest

And the latest work_amend date is later than this expression's date:

- don't generate the normal 'this is the latest' notice
- do generate the new notice as a warning.

**Comment by goose-life** [comment]
Similarly to the `this version` pill next to the current point in time, I suggest an `unapplied amendment` pill (perhaps in grey?) next to the more recent points in time.

@longhotsummer thoughts?

![image](https://user-images.githubusercontent.com/32566441/206111816-0628b533-e12f-454c-95f1-61aad68cb625.png)

**Comment by longhotsummer** [comment]
I think the extra pill is a good idea. I think sthing like "not yet applied" or "outstanding" is more descriptive than "unapplied", indicating it's still being worked on.

**Comment by goose-life** [comment]
I think let's go with `amendment not yet applied`

**Comment by goose-life** [comment]
I assume the view will have to do the logic here:
If there is a work_amendment and no associated expression, add a flag or something, and then the template renders the pill for that flag?
