### ISSUE TITLE
As an editor I would like gazettes to be ingested from gazettes.africa automatically

### ISSUE THREAD

**Issue by actlikewill** [laws-africa/peachjam#699]
With better support for gazettes now available on Peachjam websites, we need a mechanism to pull in documents from Gazettes.Africa

## Proposal
 * Create a new Adapter that will connect directly to the `Gazettes.Africa database and pull in relevant gazettes that are relevant the current LII website.
* Leverage the Django's ability to work with multiple databases, and the fact that the Gazettes.Africa is now based on Peachjam, to create a workflow that will do the following: 
    - Set up an ingestor that will contain configuration for the LII websites connect to a new GazettesAdapter.
    - Create a new `GazettesAdapter` the will contain logic to fetch and update any relevant gazettes. 
    - Set up a background task that will wake up every x minutes to check if any new gazettes need to be ingestion and queue up the ingestor to pull them in.

#### Ingestor Settings
* jurisdiction

#### GazettesAdapter

- *For Update*:
        - Have an update method that will query the gazettes.africa database that will filter for documents according the the jurisdiction in the ingestor settings and last updated at date
        - Copy any new gazettes in to the Peachjam database
- *For Delete*
        - Have a delete method that will compare both Gazettes objects to check which exist on the Peachjam LII but not on Gazettes.Africa and delete them

**Comment by longhotsummer** [comment]
How will the more frequent background task be handled? If it's hard-coded, then it will need to know what ingestor to fire up, which very flexible or practical. Perhaps an ingestor setting that is checked when django starts up, and defaults to 24 hours? So the current behaviour becomes the default, but can be adjusted.

**Comment by longhotsummer** [comment]
Closed by https://github.com/laws-africa/peachjam/pull/716
