### ISSUE TITLE
As a user I would like to view changed provisions of document on mobile

### ISSUE THREAD

**Issue by musangowope** [laws-africa/peachjam#708]
Proposed mobile design:
Similar to annotations, an icon is displayed in the gutter on the same level as its associated content. I chose a clock icon to denote change over time.
![Icon view](https://user-images.githubusercontent.com/15995210/204309861-b09f1f87-07ea-435b-a099-345ccafdc6a2.png)

on click of the clock icon, a modal is displayed, showing the what changed provision content:
![Modal](https://user-images.githubusercontent.com/15995210/204310581-54cd15b2-aad7-49a2-8947-a57475ad96dd.png)

For a side-by-side viewing, perhaps we could have a horizontal overflow content scroll?

**Comment by musangowope** [comment]
@longhotsummer let me know what you think about this

**Comment by longhotsummer** [comment]
🤔 

Do you mean a proper "popup" modal, or is the diff embedded exactly as it is on desktop? I think the latter is much simpler.

I like the history icons -- it should fit in with how you did the annotation markers on mobile, right?

Either horizontal scroll, or disable the side-by-side. But horizontal scroll on the "modal" content is reasonable. You'll need to set a minimum width on the columns.
