### ISSUE TITLE
As a user, I want to be able to filter results by document type when browsing AU Documents so that I can look through documents of the type I am interested in.

### ISSUE THREAD

**Issue by IngeNuWitty** [laws-africa/peachjam#714]
As a user who wants to see guidelines for submitting a complaint to an AGP organ, I know that there may be formal rules or guidelines for doing this and want to look at those, but I may not know exactly what the document is called. I may click on AU Documents or Treaties and Protocols thinking they are there, but I can't filter by document type and therefore have to scroll through lots of irrelevant documents. I have only one choice which is to go back to the main search field and search with the word 'guidelines [organ]' or 'rules [organ]', which is not user-friendly and depending on the terms I use, may not lead me to the results I need.

**Comment by longhotsummer** [comment]
I think extra document-type filters in more generic document listing views is +1.

This will also be impacted by #601

**Comment by longhotsummer** [comment]
In the short term, adding a Doc Nature facet to https://agp.africanlii.org/generic_documents/ would be very useful.

**Comment by longhotsummer** [comment]
Largely resolved by #890. The nature filtering on the author view is covered by #638
