### ISSUE TITLE
As a legislation user I want to see translations applicable for my chosen language

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#737]
We need the javascript legislation listing view to use similar logic to https://github.com/laws-africa/peachjam/pull/698 to ensure that the best language version is shown to the user, and to indicate that there are translated versions available.

Here's an example of what must be fixed. This page is in English mode, and the current list lands up choosing an arbitrary document language for the Constitution, rather than using English because that is available.

![image](https://user-images.githubusercontent.com/4178542/205627566-11b7ca6d-aa52-4821-9a6c-9bb80d5fcfba.png)

**Comment by musangowope** [comment]
@longhotsummer Currently each legislation row has this shape
```
{
    "title": "Magistrates' Courts Act, 1944",
    "children": [],
    "citation": "Act 32 of 1944",
    "work_frbr_uri": "/akn/za/act/1944/32",
    "repealed": false,
    "year": 1984,
    "taxonomies": []
  },
```

To implement the functionality of showing legislation applicable to my language chosen, I propose we change the shape of the data served to the front end to something like this?
```
[
    {
          "versions": {
            "fra": {
              "title": "Magistrates' Courts Act, 1944 French",
              "children": [],
              "citation": "Act 32 of 1944",
              "work_frbr_uri": "/akn/za/act/1944/32"
            },
            "spa": {
              "title": "Magistrates' Courts Act, 1944 Spanish",
              "children": [],
              "citation": "Act 32 of 1944",
              "work_frbr_uri": "/akn/za/act/1944/32"
            }
          },
          "repealed": false,
          "year": 1984,
          "taxonomies": []
        },
        {
          "versions": {
            "eng": {
              "title": "Magistrates' Courts Amendment Act, 1952",
              "children": [],
              "citation": "Act 40 of 1952",
              "work_frbr_uri": "/akn/za/act/1952/40"
            }
       },
]
```

So the front end has the relevant translations to decide which legislation to show
