### ISSUE TITLE
As a user of the AGP website, I would like to be able to discover if my African country has ratified a legal instrument

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#760]
and when was the adoption finalised.

**Comment by actlikewill** [comment]
# Proposal

#### Model
Add a Ratification Model to peachjam with the following fields:
 - **work** - ForeignKey to the Work model
 - **country** - ForeignKey to Country Model
 - **ratification_date** - DateField
 - **deposit_date** - Datefield
 - **signature_date** - DateField

#### Detail View
Add a `Ratifications` tab to the the document details page that when clicked shows queries the above model and shows a table with list of countries that ratified the legal instrument and the dates. Include a count of the countries in the tab.

#### Admin
Add the Ratifications Model as an inline to the Work Model for manual editing

**Comment by longhotsummer** [comment]
Nice. Are any of the date fields required / optional? Is there a unique compound index on any of the fields to avoid capturing a country twice?

**Comment by actlikewill** [comment]
@longhotsummer Thanks. I've updated the proposal. All the dates can be null and the we can have the country and work fields be unique together.

**Comment by longhotsummer** [comment]
Looks good!

**Comment by longhotsummer** [comment]
Once this is done, we can use https://github.com/laws-africa/peachjam/issues/598 to make the table sortable.
