### ISSUE TITLE
Search terms carried from main search into Document content search does not work for complex searches

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#762]
https://agp.africanlii.org/akn/aa-au/judgment/achpr/2008/86/eng@2008-05-22?q=%22political%20participation%22%20%22freedom%20of%20expression%22

![image](https://user-images.githubusercontent.com/46931873/206905550-d7e8ce3c-760b-4b8c-b887-fb3a14470ce0.png)

it does pick up when the search terms are modified to fit the expected input
![image](https://user-images.githubusercontent.com/46931873/206905601-40decb8a-1440-4284-982f-ad21f1f1edcf.png)

**Comment by longhotsummer** [comment]
This feature is now disabled.
