### ISSUE TITLE
As a user of the AGP site, I would like to see the language versions of generic documents

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#763]
e.g. these three documents are the language versions of the same work

https://agp.africanlii.org/akn/aa-au/doc/2022-11-23/regulamentos-referentes-a-criacao-e-funcionamento-do-mecanismo-de-alerta-e-de-prestacao-de-informacoes-a-comissao-africana-dos-direitos-humanos-e-dos-povos-sobre-situacoes-de-tortura-e-outros-tratamentos-ou-castigos-crueis-desumanos-ou-degradantes-regulamentos-de-abidjan/por@2022-11-23

https://agp.africanlii.org/akn/aa-au/doc/2022-11-23/rules-on-the-establishment-and-operation-of-the-alert-and-reporting-mechanism-to-the-african-commission-on-human-and-peoples-rights-on-situations-of-torture-and-other-cruel-inhuman-or-degrading-treatment-or-punishment-abidjan-rules/eng@2022-11-23

https://agp.africanlii.org/akn/aa-au/doc/2022-11-23/regles-portant-creation-et-fonctionnement-du-mecanisme-dalerte-et-de-rapport-a-la-commission-africaine-des-droits-de-lhomme-et-des-peuples-sur-les-situations-de-torture-et-autres-peines-ou-traitements-cruels-inhumains-ou-degradants-les-regles-dabidjan/fra@2022-11-23

**Comment by longhotsummer** [comment]
Technically, this is already supported, although it's not easy to make it happen through the admin ui. The FRBR URI for each work needs to be made the same. Because the title is part of the FRBR URI, one of the languages must be chosen as the standard FRBR URI for all the documents.

**Comment by longhotsummer** [comment]
So, for each non-English document, this field must be set to the same as is used for the English document:

![image](https://user-images.githubusercontent.com/4178542/212614420-de82f0c8-a5de-40d4-a379-95cd5925508e.png)
