### ISSUE TITLE
As a bulk importer I want to be able to import possibly many alternative citations

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#788]

**Comment by NotoriousMBB** [comment]
![image](https://user-images.githubusercontent.com/46931873/211319185-dc0538b6-6aaa-4df6-8af3-d4c1afaeb29c.png)
[![image](https://user-images.githubusercontent.com/46931873/211319186-6fe05804-fdf8-4ba9-852a-3b194e27f571.png)]

https://lawlibrary.org.za/akn/za/judgment/zasca/2020/146/eng@2020-11-13

**Comment by nickmwangemi** [comment]
@longhotsummer Do we need a separate MNC model so that we can have multiple MNCs on the same judgment?

**Comment by longhotsummer** [comment]
We already have support for alternative names (citations), use that. https://github.com/laws-africa/peachjam/pull/670
