### ISSUE TITLE
As an editor I need to be able to capture attorneys on a judgment

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#789]

**Comment by longhotsummer** [comment]
@NotoriousMBB is this a blocker on SeyLII, or any others?

**Comment by longhotsummer** [comment]
@nickmwangemi this is a good candidate for the new field issue template

**Comment by NotoriousMBB** [comment]
Blocker for TanzLII. Please prioritise as we want to demo with real data
the week after

**Comment by nickmwangemi** [comment]
# Add attorneys field to Judgment

## Questions
1. What document types does the new field apply to?
    - This applies to the Judgment document type
2. Is the new field related to any other fields, such as court or jurisdiction?
    - 
3. What countries does the new field apply to?
    - Tanzania
4. Is the field required, or optional?
    - It's an optional field
5. Must the field be included in the document metadata display?
    - 
6. Must the field be included as a search facet?
    -
7. Must the field be included as a document listing facet? On which listing pages?
    -
8. Does it impact the MNC for judgments?
   - No.

## Implementation aspects:
[] Added to modelling?
[] Added to admin interface?
[] Added to document detail page?
[] Added as a facet on document listing pages?
[] Added as a search facet in search UI?
[] Added to elasticsearch indexing?

**Comment by nickmwangemi** [comment]
@NotoriousMBB I'd like to discuss questions 5, 6 & 7 above.
