### ISSUE TITLE
As a user on a newly migrated website, I'd like the old case URLs to still work for a while after migration

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#792]
while Google is still crawling the new migrated content.

**Comment by longhotsummer** [comment]
Some example old URLs:

* https://ulii.org/ug/judgment/court-appeal-uganda/2023/3
* https://ulii.org/ug/judgment/commercial-court-uganda/2023/3
* https://ulii.org/ug/judgment/high-court-uganda/2022/53
* https://ulii.org/ug/judgment/constitutional-court-uganda/2023/1


So these are very close to the new FRBR URI format. We'll need to map from the court name to a court code, eg. "high-court-uganda" -> "hcug". The rest is straight forward: /akn/ug/judgment/hcug/2022/53

**Comment by longhotsummer** [comment]
I suggest, in the short term, that we simply hard-code the mappings into the LII.

**Comment by actlikewill** [comment]
@longhotsummer Do you have the court code mappings?

**Comment by NotoriousMBB** [comment]
The pattern is
ug/judgment/[node:field_court_name:entity]/[node:field_date:date:custom:Y]/[node:field_judgment_number:value]

The Court codes are

Leadership Code Tribunal of Uganda  -  UGLCT
Supreme Court of Uganda -- UGSC
Court of Appeal of Uganda -- UGCA
Constitutional Court of Uganda -- UGCC
Commercial Court of Uganda -- UGCommC
Industrial Court of Uganda -- UGIC
High Court of Uganda -- UGHC
HC: Civil Division (Uganda) -- UGHCCD
HC: Criminal Division (Uganda) -- UGHCCRD
HC: Family Division (Uganda) -- UGHCFD
HC: Land Division (Uganda) -- UGHCLD
HC: International Crimes Division (Uganda) -- UGHICD
HC: Anti corruption Division (Uganda) -- UGHCACD
High Court: Execution and Bailiffs Division (Uganda) -- UGHCEBD
Election Petitions of Uganda -- UGHCEP
Equal Opportunities Commission -- UGEOC
Center for Arbitration and Dispute Resolution of Uganda -- UGCADER
Tax Appeals Tribunal (Uganda) -- UGTAT

**Comment by NotoriousMBB** [comment]
The name of the court is transformed in the URL pattern with the following rules
![image](https://user-images.githubusercontent.com/46931873/212858937-37f0ff50-1085-49d1-b700-3a7e69baa3f5.png)
