### ISSUE TITLE
As a user of the AGP website, I would like to be able to filter the AU documents category by document nature

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#814]
https://agp.africanlii.org/generic_documents/  similar to the output in search results for document type and document nature

![image](https://user-images.githubusercontent.com/46931873/212672663-3a169c5c-4c38-4e19-9308-7d8245bda96b.png)

![image](https://user-images.githubusercontent.com/46931873/212672815-aabc8ff6-dffd-4ff4-b362-c8e8a6b19381.png)

**Comment by longhotsummer** [comment]
Some thoughts:

* change `/generic_document` to be `/doc` to match the new generic-document-nature view (`/doc/<nature>`)
* ensure `/doc` works appropriately
* add a `nature` facet (not doctype) on the `/doc` view
