### ISSUE TITLE
Add a link to the landing page of the Forensic Science library on LawLibrary

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#848]
Add a link to the landing page of the Forensic Science library
https://lawlibrary.org.za/taxonomy/collections/forensic-science

**Comment by longhotsummer** [comment]
The suggest is that we change "SGBV" in the top-level nav into "Collections", as well as link to it from the landing page somehow (perhaps show the top-level taxonomy list).

**Comment by nickmwangemi** [comment]
Partially resolved by #863
