### ISSUE TITLE
As an admin I need to be able to bulk import flynotes for judgments

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#882]
We currently are unable to migrate flynotes with caselaw records. The feature is used across several sites. Could we discuss a way forward?
![image](https://user-images.githubusercontent.com/46931873/215262579-240566a3-8e27-499e-a422-adc66a91fb1a.png)

**Comment by longhotsummer** [comment]
@actlikewill pls confirm this is in place and close it if so.

**Comment by actlikewill** [comment]
This is in place. The column name should be `flynote` singular
