### ISSUE TITLE
Updated AGP homepage content based on new site navigation

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#910]
Once #909 is done

**Comment by longhotsummer** [comment]
The idea here is to give the user an entry point into the site's content from the homepage, as well as a teaser of recent documents for each document type. I'll provide more details today.

**Comment by longhotsummer** [comment]
![image](https://user-images.githubusercontent.com/4178542/221512722-489eaee5-517f-400b-8713-6f0493f7b69c.png)

* leave regional bodies at the top as-is
* leave "Recent Judgments" as is
* "Recent AU Documents" changes to be "Recent Legal Instruments" and the documents listed should be the same docs listed under https://agp.africanlii.org/legal-instruments/
* "Recent Legal Instruments" changes to "Recent Soft Law" and the documents listed should be the same docs listed under https://agp.africanlii.org/soft-law/
* Skip the "African Union" section for now as we don't have that data yet
* Skip Topics for same reason
* new section "Recent Reports & Guides" which lists recent docs as per https://agp.africanlii.org/doc/
* Finally "Latest Commentary" remains

**Comment by actlikewill** [comment]
@longhotsummer Should we leave "Recent Treaties and Protocols" as is?

**Comment by longhotsummer** [comment]
It must match the new header nav which doesn't have treaties and protocols.
