### ISSUE TITLE
AGP site: upload and link from Main menu help information

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#921]
First draft (to be updated next month) available here
https://docs.google.com/document/d/1uJyT-1unQdKxSyGlf3h-j4Nh8Ihf9qqrdEHLalrO0Lc/edit?usp=sharing

Impact: high due to need to report link to EU

**Comment by longhotsummer** [comment]
I've uploaded here for the interim: https://laws-africa.gitbook.io/africanlii/

We need a "Help" link on the main navbar, to the right of "About", that opens that link in a new tab.

**Comment by longhotsummer** [comment]
Further edits can be made here: https://app.gitbook.com/o/-LoitctXFtxngZR4OieO/s/a3vFbB9iKJ7awfpxPe4J/
