### ISSUE TITLE
Create a metadata field for Registry - controlled vocabulary - in the Judgment content type

### ISSUE THREAD

**Issue by NotoriousMBB** [laws-africa/peachjam#943]
the alternative is to use locality, but this is not strictly accurate.
This is a block in Tanzania and a request in Uganda.

Update importer to include the field so migration on TanzLII can continue

**Comment by nickmwangemi** [comment]
# Proposal

# Create a Registry model
Create a Registry model on peachjam with the following fields:
- `court` - Foreign Key linking to the Court model
- `name` -  name of the registry


## Background
The Registry model could be thought of as an "office" of the court, hence links back to a court. i.e. a Court can have multiple registries.

## Constraints and Assumptions
This is a fixed list of items that can be managed in the admin area.
Make the court and name fields unique together.
