### ISSUE TITLE
Ops: group most liis under one sentry app

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#961]
All LIIs except lawlibrary and africanlii should be under one sentry app URL

**Comment by actlikewill** [comment]
@nickmwangemi didn't you already do this?

**Comment by nickmwangemi** [comment]
I did. We can sanity check just to be sure

**Comment by longhotsummer** [comment]
Thanks, I didn't realise this. I see it in sentry. Pls sanity check that all the new liis have the correct env setting and this can be closed.
