### ISSUE TITLE
Finalize NamibLII Migrations

### ISSUE THREAD

**Issue by niiroobiro** [laws-africa/peachjam#979]
# Checklist

* [ ] Homepage Menu List
* [x] Hero Banner
* [x] About Page Text/Link/Information
* [x] About in Footer Text
* [x] Newsletter Link if any - no mailing list
* [ ] Google Analytics - get from view source
* [x] Partner Logos on the homepage/With support from
* [ ] Terms of Use - add link in footer,  parameterize terms of use page
* [x] Contact Information

# Homepage Menu List
---
### Top Menu Bar
* Menu  Items- Judgements, Legislation, Gazettes, 
* Add Link to About Page
* Language Options- This needs further discussion.
### Right Sidebar
* Add About Information
NamibLII is a project of the Law Reform and Development Commission and a member of the global Free Access to Law Movement and the AfricanLII community.
* Add Social Media block- Refer here: (https://namiblii.org/about)
### Hero Banner Area

* Copy the text  from https://namiblii.org/
Welcome to the Namibia Legal Information Institute
NamibLII publishes the law of Namibia for free access to all. We are a member of the international free access to law movement. Read, use, and share the law freely.
* High-Resolution Logos
AfricanLII, Laws.Africa, Legal Assistance Center

### Footer
* About NamibLII
NamibLII is a project of the Law Reform and Development Commission managed by the Directorate: Law Reform of the Ministry of Justice of the Republic of Namibia.

In terms of the Law Reform and Development Commission Act, 1991 (Act No. 29 of 1991) the Commission is mandated to consolidate or codify any branch of the law or to introduce other measures aimed at making the law more readily accessible.

NamibLII is the embodiment of this mandate making annotated statutes, judgments, and gazettes available in a user-friendly format. 
* Add With Support From- Get this from the old site (https://namiblii.org/about)
* New About page ( Link it to the top menu)
-Copy the text of the About page from here: https://namiblii.org/about

### Partners

AfricanLII
Laws.Africa
Legal Assistance Centre

### Contact Information
We get this from the old site.

**Comment by actlikewill** [comment]
@niiroobiro We still don't have details for links to Law Reform Reports, LRDC Reports and Covid-19 Legislation, so I will ignore those for now until you can get them.

**Comment by niiroobiro** [comment]
@actlikewill That's okay. Let's work with what we have for now.
